const $ = (s) => document.querySelector(s);

const categories = [
  {id:'gis', title:'GİS Kanama', subtitle:'Üst GİS kanaması', icon:'G', description:'Üst gastrointestinal sistem kanamasında erken risk değerlendirmesi.', scores:['gbs']},
  {id:'aks', title:'AKS', subtitle:'Göğüs ağrısı', icon:'♥', description:'Akut koroner sendrom ve göğüs ağrısında risk sınıflaması.', scores:['timi','heart','grace']},
  {id:'tia', title:'TİA', subtitle:'Erken inme riski', icon:'A', description:'Geçici iskemik atak sonrası erken dönem inme riski.', scores:['abcd2']},
  {id:'pnomoni', title:'Pnömoni', subtitle:'CAP ciddiyeti', icon:'P', description:'Toplum kökenli pnömonide mortalite ve yatış risk değerlendirmesi.', scores:['curb65','psi']},
  {id:'dvt', title:'DVT', subtitle:'Klinik olasılık', icon:'D', description:'Derin ven trombozu için klinik ön test olasılığı.', scores:['wellsDvt']},
  {id:'pe', title:'PE', subtitle:'Klinik olasılık', icon:'E', description:'Pulmoner emboli için klinik ön test olasılığı ve dışlama ölçütleri.', scores:['wellsPe','perc']},
  {id:'senkop', title:'Senkop', subtitle:'Ciddi sonuç riski', icon:'S', description:'Senkopta kısa dönem ciddi sonuç risk taraması.', scores:['sfsr']}
];

const yes = (id,label,help='',points=1) => ({type:'toggle',id,label,help,points});
const num = (id,label,unit,min=0,max=999,step=1,help='',required=true) => ({type:'number',id,label,unit,min,max,step,help,required});
const choice = (id,label,options,help='') => ({type:'choice',id,label,options,help,required:true});

const sources = {
  gbs:'Blatchford O, Murray WR, Blatchford M. Lancet. 2000;356:1318–1321.',
  timi:'Antman EM, et al. JAMA. 2000;284:835–842.',
  heart:'Six AJ, Backus BE, Kelder JC. Neth Heart J. 2008;16:191–196.',
  grace:'Granger CB, et al. Arch Intern Med. 2003;163:2345–2353. GRACE 1.0 kabul puanı.',
  abcd2:'Johnston SC, et al. Lancet. 2007;369:283–292.',
  curb65:'Lim WS, et al. Thorax. 2003;58:377–382.',
  psi:'Fine MJ, et al. N Engl J Med. 1997;336:243–250.',
  wellsDvt:'Wells PS, et al. Lancet. 1997;350:1795–1798; değiştirilmiş iki düzeyli model.',
  wellsPe:'Wells PS, et al. Thromb Haemost. 2000;83:416–420.',
  perc:'Kline JA, et al. J Thromb Haemost. 2008;6:772–780.',
  sfsr:'Quinn JV, et al. Ann Emerg Med. 2004;43:224–232.'
};

const scores = {
  gbs:{title:'Glasgow-Blatchford',short:'Blatchford',description:'Üst GİS kanamasında müdahale veya transfüzyon gereksinimi riskini öngörür.',sections:[
    ['Hasta bilgileri',[choice('sex','Cinsiyet',[['male','Erkek'],['female','Kadın']]),num('bun','BUN','mg/dL',0,200,.1,'Kan üre azotu'),num('hb','Hemoglobin','g/dL',1,25,.1),num('sbp','Sistolik kan basıncı','mmHg',30,300,1),num('hr','Kalp hızı','/dk',20,300,1)]],
    ['Klinik bulgular',[yes('melena','Melena'),yes('syncope','Senkop'),yes('liver','Karaciğer hastalığı'),yes('heartFailure','Kalp yetersizliği')]]
  ],calc:v=>{let s=0;const b=v.bun;if(b>=70)s+=6;else if(b>=28)s+=4;else if(b>=22.4)s+=3;else if(b>=18.2)s+=2;if(v.sex==='male'){if(v.hb<10)s+=6;else if(v.hb<12)s+=3;else if(v.hb<13)s+=1}else{if(v.hb<10)s+=6;else if(v.hb<12)s+=1}if(v.sbp<90)s+=3;else if(v.sbp<100)s+=2;else if(v.sbp<110)s+=1;if(v.hr>=100)s++;if(v.melena)s++;if(v.syncope)s+=2;if(v.liver)s+=2;if(v.heartFailure)s+=2;return s<=1?res(s,'Çok düşük risk','GBS 0–1, uygun hastada ayaktan yönetim adayı olabilir. Klinik durum ve yerel protokol ile birlikte değerlendirin.','low','Skor; endoskopi, yatış ya da taburculuk kararını tek başına belirlemez.'):res(s,'Artmış müdahale riski','Hastane temelli değerlendirme ve uygun acil yönetim gerekir. Skor yükseldikçe müdahale gereksinimi artar.',s<6?'mid':'high','Hemodinamik instabilitede skoru beklemeden resüsitasyona başlayın.')}} ,
  timi:{title:'TIMI UA/NSTEMI',short:'TIMI',description:'UA/NSTEMI’de 14 günlük ölüm, MI veya acil revaskülarizasyon riskini sınıflar.',sections:[['Her biri 1 puan',[yes('age65','Yaş ≥65'),yes('risk3','≥3 KAH risk faktörü','HT, DM, dislipidemi, aile öyküsü, aktif sigara'),yes('knownCad','Bilinen KAH','Koroner darlık ≥%50'),yes('asa','Son 7 günde ASA kullanımı'),yes('angina','Son 24 saatte ≥2 anjina atağı'),yes('st','ST deviasyonu ≥0,5 mm'),yes('marker','Pozitif kardiyak belirteç')]]],calc:v=>{const s=sumToggles(v);const risks=[4.7,4.7,8.3,13.2,19.9,26.2,40.9];return res(s,s<=2?'Düşük risk':s<=4?'Orta risk':'Yüksek risk',`Orijinal kohortta 14 günlük birleşik olay riski yaklaşık %${risks[s]}.`,s<=2?'low':s<=4?'mid':'high','Yalnız UA/NSTEMI şüphesinde ve klinik değerlendirmeyle birlikte kullanın.')}},
  heart:{title:'HEART Skoru',short:'HEART',description:'Acil serviste göğüs ağrısı olan hastalarda 6 haftalık majör kardiyak olay riskini değerlendirir.',sections:[['HEART bileşenleri',[choice('history','Öykü',[['0','Hafif şüpheli'],['1','Orta şüpheli'],['2','Çok şüpheli']]),choice('ecg','EKG',[['0','Normal'],['1','Nonspesifik repolarizasyon bozukluğu'],['2','Belirgin ST depresyonu']]),num('age','Yaş','yıl',18,120,1),choice('risk','Risk faktörleri',[['0','Yok'],['1','1–2 risk faktörü'],['2','≥3 risk faktörü / bilinen ateroskleroz']],'HT, DM, dislipidemi, obezite, sigara, aile öyküsü'),choice('troponin','Troponin',[['0','≤ normal sınır'],['1','Normal sınırın 1–3 katı'],['2','>3 katı']],'Kullandığınız testin üst referans sınırına göre')]]],calc:v=>{const s=+v.history + +v.ecg + (v.age>=65?2:v.age>=45?1:0) + +v.risk + +v.troponin;return s<=3?res(s,'Düşük risk','6 haftalık MACE riski yaklaşık %1,7. Uygun seri troponin algoritması ve klinik değerlendirme gereklidir.','low'):s<=6?res(s,'Orta risk','6 haftalık MACE riski yaklaşık %16,6. Gözlem ve ileri değerlendirme düşünülür.','mid'):res(s,'Yüksek risk','6 haftalık MACE riski yaklaşık %50,1. Erken invaziv değerlendirme gündeme gelir.','high','HEART, akut göğüs ağrısı değerlendirmesinin tamamlayıcısıdır.')}},
  grace:{title:'GRACE',short:'GRACE',description:'Akut koroner sendromda hastane içi mortalite riskini GRACE 1.0 kabul puanıyla sınıflar.',sections:[['Başvuru verileri',[num('age','Yaş','yıl',18,120,1),num('hr','Kalp hızı','/dk',20,300,1),num('sbp','Sistolik kan basıncı','mmHg',30,300,1),num('creat','Kreatinin','mg/dL',.1,15,.1),choice('killip','Killip sınıfı',[['1','I — Kalp yetersizliği yok'],['2','II — Raller / S3 / JVD'],['3','III — Pulmoner ödem'],['4','IV — Kardiyojenik şok']])]],['Ek bulgular',[yes('arrest','Başvuruda kardiyak arrest'),yes('st','ST segment deviasyonu'),yes('marker','Yüksek kardiyak belirteç')]]],calc:v=>{let s=band(v.age,[[30,0],[40,8],[50,25],[60,41],[70,58],[80,75],[90,91],[Infinity,100]]);s+=band(v.hr,[[50,0],[70,3],[90,9],[110,15],[150,24],[200,38],[Infinity,46]]);s+=band(v.sbp,[[80,58],[100,46],[120,36],[140,26],[160,18],[180,10],[200,4],[Infinity,0]]);s+=band(v.creat,[[.4,1],[.8,4],[1.2,7],[1.6,10],[2,13],[4,21],[Infinity,28]]);s+=({1:0,2:20,3:39,4:59})[v.killip];if(v.arrest)s+=39;if(v.st)s+=28;if(v.marker)s+=14;return s<=108?res(s,'Düşük hastane içi risk','GRACE ≤108: hastane içi mortalite için düşük risk sınıfı (<%1).','low'):s<=140?res(s,'Orta hastane içi risk','GRACE 109–140: orta risk sınıfı (yaklaşık %1–3).','mid'):res(s,'Yüksek hastane içi risk','GRACE >140: yüksek risk sınıfı (>%3); erken invaziv strateji açısından önemlidir.','high','Bu araç GRACE 1.0 kabul puanını ve risk sınıfını verir; GRACE 2.0 yüzdesi değildir.')}},
  abcd2:{title:'ABCD²',short:'ABCD²',description:'TİA sonrası 2 günlük erken inme riskini tahmin eder.',sections:[['Klinik bilgiler',[num('age','Yaş','yıl',18,120,1),num('sbp','Sistolik kan basıncı','mmHg',50,300,1),num('dbp','Diyastolik kan basıncı','mmHg',20,200,1),choice('clinical','Klinik özellik',[['2','Tek taraflı güçsüzlük'],['1','Güçsüzlük olmadan konuşma bozukluğu'],['0','Diğer']]),choice('duration','Semptom süresi',[['2','≥60 dakika'],['1','10–59 dakika'],['0','<10 dakika']]),yes('diabetes','Diyabetes mellitus')]]],calc:v=>{const s=(v.age>=60?1:0)+((v.sbp>=140||v.dbp>=90)?1:0)+ +v.clinical + +v.duration +(v.diabetes?1:0);return s<=3?res(s,'Düşük risk','Orijinal doğrulamada 2 günlük inme riski yaklaşık %1,0.','low'):s<=5?res(s,'Orta risk','Orijinal doğrulamada 2 günlük inme riski yaklaşık %4,1.','mid'):res(s,'Yüksek risk','Orijinal doğrulamada 2 günlük inme riski yaklaşık %8,1.','high','ABCD², vasküler görüntüleme ve uzman değerlendirmesinin yerine geçmez; düşük skor güvenli taburculuk anlamına gelmez.')}},
  curb65:{title:'CURB-65',short:'CURB-65',description:'Toplum kökenli pnömonide 30 günlük mortalite riskini sınıflar.',sections:[['Başvuru verileri',[yes('confusion','Yeni konfüzyon'),num('bun','BUN','mg/dL',0,200,.1,'>19 mg/dL ise 1 puan'),num('rr','Solunum sayısı','/dk',5,80,1),num('sbp','Sistolik kan basıncı','mmHg',30,300,1),num('dbp','Diyastolik kan basıncı','mmHg',20,200,1),num('age','Yaş','yıl',18,120,1)]]],calc:v=>{const s=(v.confusion?1:0)+(v.bun>19?1:0)+(v.rr>=30?1:0)+((v.sbp<90||v.dbp<=60)?1:0)+(v.age>=65?1:0);const mortality=[.7,3.2,3,17,41.5,57][s];return s<=1?res(s,'Düşük risk',`Orijinal çalışmada 30 günlük mortalite yaklaşık %${mortality}. Ayaktan tedavi uygunluğu klinikle belirlenir.`,'low'):s===2?res(s,'Orta risk',`Orijinal çalışmada 30 günlük mortalite yaklaşık %${mortality}. Kısa yatış / hastane gözetimi düşünülür.`,'mid'):res(s,'Yüksek risk',`Orijinal çalışmada 30 günlük mortalite yaklaşık %${mortality}. Yatış ve özellikle ≥4 puanda yoğun bakım değerlendirmesi düşünülür.`,'high','Oksijenasyon ve IDSA/ATS ağır pnömoni ölçütleri ayrıca değerlendirilmelidir.')}},
  psi:{title:'PSI / PORT',short:'PSI',description:'Toplum kökenli pnömonide 30 günlük mortaliteyi 20 değişkenle sınıflar.',sections:[['Demografi',[choice('sex','Cinsiyet',[['male','Erkek'],['female','Kadın']]),num('age','Yaş','yıl',18,120,1),yes('nursing','Bakımevinde yaşama')]],['Komorbidite',[yes('cancer','Neoplastik hastalık'),yes('liver','Karaciğer hastalığı'),yes('chf','Kalp yetersizliği'),yes('cvd','Serebrovasküler hastalık'),yes('renal','Böbrek hastalığı')]],['Fizik muayene',[yes('mental','Bilinç değişikliği'),num('hr','Kalp hızı','/dk',20,300,1),num('rr','Solunum sayısı','/dk',5,80,1),num('sbp','Sistolik kan basıncı','mmHg',30,300,1),num('temp','Vücut sıcaklığı','°C',25,45,.1)]],['Laboratuvar ve görüntüleme — ölçülmediyse boş bırakın',[num('ph','Arteriyel pH','',6.5,8,.01,'Ölçülmediyse boş bırakın',false),num('bun','BUN','mg/dL',0,200,.1,'Ölçülmediyse boş bırakın',false),num('na','Sodyum','mmol/L',80,200,1,'Ölçülmediyse boş bırakın',false),num('glucose','Glukoz','mg/dL',10,1000,1,'Ölçülmediyse boş bırakın',false),num('hct','Hematokrit','%',5,70,.1,'Ölçülmediyse boş bırakın',false),num('pao2','PaO₂','mmHg',20,700,1,'Oda havasında; ölçülmediyse boş bırakın',false),yes('hypoxemia','SpO₂ <%90','PaO₂ girilmediyse kullanılabilir'),yes('effusion','Plevral efüzyon')]]],calc:v=>{const step1=v.age<50&&!v.cancer&&!v.liver&&!v.chf&&!v.cvd&&!v.renal&&!v.mental&&v.hr<125&&v.rr<30&&v.sbp>=90&&v.temp>=35&&v.temp<40;if(step1)return res('I','Risk sınıfı I','30 günlük mortalite yaklaşık %0,1; ayaktan tedavi adayı olabilir.','low','Sosyal durum, oral alım, oksijenasyon ve klinik yargı ayrıca değerlendirilir.');let s=v.age-(v.sex==='female'?10:0)+(v.nursing?10:0)+(v.cancer?30:0)+(v.liver?20:0)+(v.chf?10:0)+(v.cvd?10:0)+(v.renal?10:0)+(v.mental?20:0)+(v.hr>=125?10:0)+(v.rr>=30?20:0)+(v.sbp<90?20:0)+((v.temp<35||v.temp>=40)?15:0)+((v.ph!=null&&v.ph<7.35)?30:0)+((v.bun!=null&&v.bun>=30)?20:0)+((v.na!=null&&v.na<130)?20:0)+((v.glucose!=null&&v.glucose>=250)?10:0)+((v.hct!=null&&v.hct<30)?10:0)+(((v.pao2!=null&&v.pao2<60)||v.hypoxemia)?10:0)+(v.effusion?10:0);const cls=s<=70?'II':s<=90?'III':s<=130?'IV':'V';const data={II:['%0,6','Ayaktan tedavi adayı','low'],III:['%0,9','Kısa gözlem / ayaktan tedavi düşünülebilir','low'],IV:['%9,3','Yatarak tedavi genellikle uygundur','mid'],V:['%27,0','Yatarak tedavi; yoğun bakım gereksinimini ayrıca değerlendir','high']}[cls];return res(`${s} · ${cls}`,`Risk sınıfı ${cls}`,`30 günlük mortalite yaklaşık ${data[0]}. ${data[1]}.`,data[2],'Eksik laboratuvar değişkenleri 0 puan kabul edilmiştir. PSI, yoğun bakım gereksinimini tek başına belirlemez.')}},
  wellsDvt:{title:'Wells DVT',short:'Wells DVT',description:'DVT için değiştirilmiş iki düzeyli klinik ön test olasılığı.',sections:[['Klinik ölçütler',[yes('cancer','Aktif kanser','Son 6 ay tedavi veya palyatif'),yes('paralysis','Paralizi / parezi / alt ekstremite alçısı'),yes('bed','≥3 gün yatak istirahati veya son 12 haftada büyük cerrahi'),yes('tender','Derin ven trasesinde lokal hassasiyet'),yes('leg','Tüm bacakta şişlik'),yes('calf','Baldır çevresi farkı ≥3 cm'),yes('edema','Semptomatik bacakta gode bırakan ödem'),yes('collateral','Kollateral yüzeyel venler','Variköz olmayan'),yes('previous','Önceki DVT'),yes('alternative','Alternatif tanı en az DVT kadar olası','−2 puan',-2)]]],calc:v=>{let s=0;for(const [k,val] of Object.entries(v))if(val)s+=k==='alternative'?-2:1;return s>=2?res(s,'DVT olası','İki düzeyli Wells modelinde skor ≥2: DVT olası. Uygun görüntüleme / D-dimer algoritmasını izleyin.','high'):res(s,'DVT olası değil','İki düzeyli Wells modelinde skor <2: DVT olası değil. Uygun hastada D-dimer ile dışlama yolu kullanılabilir.','low','Antikoagülasyon ve görüntüleme kararı yerel tanı algoritmasına göre verilmelidir.')}},
  wellsPe:{title:'Wells PE',short:'Wells PE',description:'Pulmoner emboli için klinik ön test olasılığı.',sections:[['Klinik ölçütler',[yes('dvt','DVT klinik bulguları','Bacak şişliği ve derin ven palpasyonunda ağrı',3),yes('alternative','PE alternatif tanıdan daha olası','Klinisyen değerlendirmesi',3),yes('hr','Kalp hızı >100/dk','',1.5),yes('immobilization','Son 4 haftada ≥3 gün immobilizasyon veya cerrahi','',1.5),yes('previous','Önceki DVT / PE','',1.5),yes('hemoptysis','Hemoptizi','',1),yes('cancer','Aktif malignite','Tedavi sürüyor, son 6 ay tedavi veya palyatif',1)]]],calc:v=>{let s=0;const pts={dvt:3,alternative:3,hr:1.5,immobilization:1.5,previous:1.5,hemoptysis:1,cancer:1};Object.keys(pts).forEach(k=>{if(v[k])s+=pts[k]});return s>4?res(s,'PE olası','İki düzeyli Wells modelinde skor >4: PE olası. Görüntüleme temelli tanı yolu uygundur.','high'):res(s,'PE olası değil','İki düzeyli Wells modelinde skor ≤4: PE olası değil. Uygun hastada D-dimer / PERC temelli dışlama yolu düşünülebilir.','low','Hemodinamik instabil PE şüphesinde standart stabil hasta algoritması uygulanmaz.')}},
  perc:{title:'PERC',short:'PERC',description:'Klinik olarak düşük riskli hastada PE’yi ek test olmadan dışlama ölçütleri.',sections:[['Ön koşul',[choice('lowRisk','Klinik gestalt ile PE olasılığı düşük mü?',[['yes','Evet — <%15'],['no','Hayır / emin değilim']],'PERC yalnız düşük ön test olasılığında uygulanır.')]],['Pozitif PERC ölçütleri',[yes('age','Yaş ≥50'),yes('hr','Kalp hızı ≥100/dk'),yes('sat','Oda havasında SpO₂ <%95'),yes('leg','Tek taraflı bacak şişliği'),yes('hemoptysis','Hemoptizi'),yes('estrogen','Ekzojen östrojen / hormon kullanımı'),yes('previous','Önceki DVT veya PE'),yes('surgery','Son 4 haftada hastaneye yatış gerektiren cerrahi veya travma')]]],calc:v=>{const s=['age','hr','sat','leg','hemoptysis','estrogen','previous','surgery'].filter(k=>v[k]).length;if(v.lowRisk!=='yes')return res(s,'PERC uygulanamaz','Ön test olasılığı düşük değilse PERC ile PE dışlanamaz. Wells/Geneva ve uygun tanı algoritmasını kullanın.','high','PERC, yalnız klinik gestalt ile düşük riskli erişkin hastalarda kullanılır.');return s===0?res(0,'PERC negatif','Sekiz ölçütün tamamı negatif. Düşük klinik olasılıkla birlikte PE ek test yapılmadan dışlanabilir.','low','Hemodinamik instabilite, gebelik veya PERC’nin doğrulanmadığı özel popülasyonlarda kullanmayın.'):res(s,'PERC pozitif','En az bir PERC ölçütü pozitif; PERC ile PE dışlanamaz. Uygun hastada D-dimer veya görüntüleme algoritmasına ilerleyin.','mid','PERC pozitifliği PE tanısı anlamına gelmez.')}},
  sfsr:{title:'San Francisco Senkop Kuralı',short:'San Francisco',description:'Senkopta kısa dönem ciddi sonuç açısından yüksek risk özelliklerini tarar.',sections:[['CHESS ölçütleri',[yes('chf','Kalp yetersizliği öyküsü'),yes('hct','Hematokrit <%30'),yes('ecg','Anormal EKG','Yeni değişiklik veya sinüs dışı ritim'),yes('sob','Nefes darlığı'),yes('sbp','Triyaj sistolik KB <90 mmHg')]]],calc:v=>{const s=sumToggles(v);return s===0?res(0,'Yüksek risk ölçütü yok','CHESS ölçütlerinin hiçbiri yok. Kural ciddi sonuç açısından düşük risk grubunu destekler.','low'):res(s,'Yüksek risk','En az bir CHESS ölçütü mevcut. Kısa dönem ciddi sonuç riski nedeniyle ileri değerlendirme gerekir.','high','Bağımsız doğrulamalarda performans değişkendir; klinik değerlendirme yerine kullanılmamalıdır.')}}
};

function res(score,title,text,tone,note=''){return{score,title,text,tone,note}}
function sumToggles(v){return Object.values(v).filter(Boolean).length}
function band(value,bands){for(const [limit,pts] of bands)if(value<limit)return pts;return 0}

let currentCategory=null,currentScore=null;
const views={home:$('#homeView'),category:$('#categoryView'),calculator:$('#calculatorView')};

function showView(name){Object.entries(views).forEach(([k,v])=>v.classList.toggle('is-hidden',k!==name));$('#backButton').classList.toggle('is-hidden',name==='home');$('#resetButton').classList.toggle('is-hidden',name!=='calculator');window.scrollTo({top:0,behavior:'instant'});}

function renderHome(){const grid=$('#categoryGrid');grid.innerHTML='';categories.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='category-card';b.innerHTML=`<span class="category-icon">${c.icon}</span><span><strong>${c.title}</strong><small>${c.subtitle}</small></span>`;b.onclick=()=>openCategory(c.id);grid.appendChild(b)});showView('home')}

function openCategory(id){currentCategory=categories.find(c=>c.id===id);$('#categoryTitle').textContent=currentCategory.title;$('#categoryDescription').textContent=currentCategory.description;const grid=$('#scoreGrid');grid.innerHTML='';currentCategory.scores.forEach(id=>{const s=scores[id],b=document.createElement('button');b.type='button';b.className='score-card';b.innerHTML=`<span><strong>${s.title}</strong><small>${s.description}</small></span><b>›</b>`;b.onclick=()=>openCalculator(id);grid.appendChild(b)});showView('category')}

function openCalculator(id){currentScore=id;const s=scores[id];$('#calculatorCategory').textContent=currentCategory.title.toUpperCase();$('#calculatorTitle').textContent=s.title;$('#calculatorDescription').textContent=s.description;const form=$('#calculatorForm');form.innerHTML='';s.sections.forEach(([title,fields])=>{const h=document.createElement('h2');h.className='section-label';h.textContent=title;form.appendChild(h);fields.forEach(f=>form.appendChild(renderField(f)))});form.oninput=calculate;$('#sourceContent').innerHTML=`<p>${sources[id]}</p><p>Hesaplayıcı yalnız erişkin hastalar ve skorun özgün kullanım popülasyonu için tasarlanmıştır.</p>`;resetResult();showView('calculator')}

function renderField(f){if(f.type==='toggle'){const e=$('#toggleTemplate').content.firstElementChild.cloneNode(true);e.querySelector('strong').textContent=f.label;e.querySelector('small').textContent=f.help;e.querySelector('input').name=f.id;return e}if(f.type==='number'){const e=$('#numberTemplate').content.firstElementChild.cloneNode(true),i=e.querySelector('input');e.querySelector('strong').textContent=f.label;e.querySelector('small').textContent=f.help;e.querySelector('em').textContent=f.unit;i.name=f.id;i.min=f.min;i.max=f.max;i.step=f.step;i.required=f.required;return e}const e=$('#selectTemplate').content.firstElementChild.cloneNode(true),box=e.querySelector('.segmented');e.querySelector('legend').textContent=f.label;e.querySelector('small').textContent=f.help;box.style.setProperty('--cols',Math.min(f.options.length,3));f.options.forEach(([value,label],idx)=>{const l=document.createElement('label');l.innerHTML=`<input type="radio" name="${f.id}" value="${value}" ${idx===-1?'checked':''}><span>${label}</span>`;box.appendChild(l)});return e}

function values(){const data={},form=$('#calculatorForm');form.querySelectorAll('input[type=checkbox]').forEach(i=>data[i.name]=i.checked);form.querySelectorAll('input[type=number]').forEach(i=>data[i.name]=i.value===''?null:+i.value);form.querySelectorAll('input[type=radio]:checked').forEach(i=>data[i.name]=i.value);return data}
function isComplete(){const form=$('#calculatorForm');let ok=true;form.querySelectorAll('.invalid').forEach(e=>e.classList.remove('invalid'));form.querySelectorAll('input[type=number]').forEach(i=>{if((i.required&&i.value==='')||(i.value!==''&&!i.checkValidity())){i.closest('.field-row').classList.add('invalid');ok=false}});const names=[...new Set([...form.querySelectorAll('input[type=radio]')].map(i=>i.name))];names.forEach(n=>{if(!form.querySelector(`input[name="${n}"]:checked`)){form.querySelector(`input[name="${n}"]`).closest('.choice-field').classList.add('invalid');ok=false}});return ok}
function calculate(){if(!isComplete()){resetResult();return}const r=scores[currentScore].calc(values()),card=$('#resultCard');card.className=`result-card ${r.tone}`;$('#resultScore').textContent=r.score;$('#resultTitle').textContent=r.title;$('#resultText').textContent=r.text;$('#resultNote').textContent=r.note;$('#resultNote').classList.toggle('is-hidden',!r.note)}
function resetResult(){const card=$('#resultCard');card.className='result-card';$('#resultScore').textContent='—';$('#resultTitle').textContent='Alanları doldurun';$('#resultText').textContent='Sonuç, tüm zorunlu alanlar tamamlandığında burada görünecek.';$('#resultNote').textContent='';$('#resultNote').classList.add('is-hidden')}

$('#backButton').onclick=()=>{if(!views.calculator.classList.contains('is-hidden'))openCategory(currentCategory.id);else renderHome()};
$('#resetButton').onclick=()=>{$('#calculatorForm').reset();$('#calculatorForm').querySelectorAll('.invalid').forEach(e=>e.classList.remove('invalid'));resetResult()};
$('.brand').onclick=e=>{e.preventDefault();renderHome()};
window.addEventListener('popstate',renderHome);
renderHome();
