const $ = (s) => document.querySelector(s);

const categories = [
  {id:'gis', title:'GİS Kanama', subtitle:'Üst GİS kanaması', icon:'droplet', description:'Üst gastrointestinal sistem kanamasında erken risk değerlendirmesi.', scores:['gbs']},
  {id:'aks', title:'AKS', subtitle:'Göğüs ağrısı', icon:'heart-pulse', description:'Akut koroner sendrom ve göğüs ağrısında risk sınıflaması.', scores:['timi','heart','grace']},
  {id:'tia', title:'TİA', subtitle:'Erken inme riski', icon:'brain', description:'Geçici iskemik atak sonrası erken dönem inme riski.', scores:['abcd2']},
  {id:'pnomoni', title:'Pnömoni', subtitle:'CAP ciddiyeti', icon:'wind', description:'Toplum kökenli pnömonide mortalite ve yatış risk değerlendirmesi.', scores:['curb65','psi']},
  {id:'dvt', title:'DVT', subtitle:'Klinik olasılık', icon:'activity', description:'Derin ven trombozu için klinik ön test olasılığı.', scores:['wellsDvt']},
  {id:'pe', title:'PE', subtitle:'Tanı ve yönetim', icon:'scan-heart', description:'Pulmoner embolide tanı, mortalite ve ayaktan tedavi uygunluğu.', scores:['wellsPe','perc','spesi','hestia']},
  {id:'senkop', title:'Senkop', subtitle:'Ciddi sonuç riski', icon:'person-standing', description:'Senkopta kısa dönem ciddi sonuç risk taraması.', scores:['sfsr']}
  ,{id:'sepsis', title:'Sepsis', subtitle:'Erken kötüleşme', icon:'thermometer', description:'Enfeksiyon şüphesinde fizyolojik kötüleşme ve mortalite riski.', scores:['news2','qsofa','shockIndex']}
  ,{id:'af', title:'Atriyal Fibrilasyon', subtitle:'İnme ve kanama', icon:'heart-pulse', description:'Atriyal fibrilasyonda tromboemboli ve kanama risk değerlendirmesi.', scores:['chadsvasc','hasbled']}
  ,{id:'abdomen', title:'Karın Ağrısı', subtitle:'Apandisit ve pankreatit', icon:'circle-dot', description:'Akut apandisit olasılığı ve pankreatit ciddiyet değerlendirmesi.', scores:['air','alvarado','bisap']}
  ,{id:'travma', title:'Travma', subtitle:'Görüntüleme kuralları', icon:'ambulance', description:'Servikal omurga ve minör kafa travmasında görüntüleme karar desteği.', scores:['canadianCspine','nexus','canadianHead']}
  ,{id:'ortho', title:'Ayak–Ayak Bileği', subtitle:'Ottawa kuralları', icon:'footprints', description:'Akut ayak ve ayak bileği travmasında grafi gerekliliği.', scores:['ottawaAnkle','ottawaFoot']}
  ,{id:'usye', title:'ÜSYE', subtitle:'Streptokok farenjiti', icon:'stethoscope', description:'Akut farenjitte Grup A streptokok olasılığı.', scores:['centor']}
  ,{id:'neuro', title:'Bilinç', subtitle:'Glasgow Koma Skalası', icon:'brain', description:'Göz, sözel ve motor yanıt üzerinden bilinç düzeyi değerlendirmesi.', scores:['gcs']}
  ,{id:'vent', title:'Mekanik Ventilasyon', subtitle:'Başlangıç ayarları', icon:'air-vent', description:'Acil serviste erişkin ve pediatrik hastalar için klinik duruma göre başlangıç ventilatör ayarları.', scores:['ventHypox','ventHypercap','ventTrauma','ventPostCpr','ventPedsTrauma']}
  ,{id:'quick', title:'Hızlı Hesaplamalar', subtitle:'Laboratuvar ve dozlama', icon:'calculator', description:'Acil serviste sık kullanılan laboratuvar ve fizyoloji hesaplamaları.', scores:['correctedNa','anionGap','correctedCa','osmolality','qtc','ibw']}
];

const yes = (id,label,help='',points=1) => ({type:'toggle',id,label,help,points});
const num = (id,label,unit,min=0,max=999,step=1,help='',required=true) => ({type:'number',id,label,unit,min,max,step,help,required});
const choice = (id,label,options,help='') => ({type:'choice',id,label,options,help,required:true});

const sources = {
  gbs:'Blatchford O, Murray WR, Blatchford M. Lancet. 2000;356:1318–1321.',
  timi:'Antman EM, et al. JAMA. 2000;284:835–842.',
  heart:'Six AJ, Backus BE, Kelder JC. Neth Heart J. 2008;16:191–196.',
  grace:'Granger CB, et al. Arch Intern Med. 2003;163:2345–2353. GRACE 1.0 kabul puanı.',
  abcd2:'Johnston SC, et al. Lancet. 2007;369:283–292.',
  curb65:'Lim WS, et al. Thorax. 2003;58:377–382.',
  psi:'Fine MJ, et al. N Engl J Med. 1997;336:243–250.',
  wellsDvt:'Wells PS, et al. Lancet. 1997;350:1795–1798; değiştirilmiş iki düzeyli model.',
  wellsPe:'Wells PS, et al. Thromb Haemost. 2000;83:416–420.',
  perc:'Kline JA, et al. J Thromb Haemost. 2008;6:772–780.',
  spesi:'Jiménez D, et al. Arch Intern Med. 2010;170:1383–1389.',
  hestia:'Zondag W, et al. J Thromb Haemost. 2011;9:1500–1507.',
  sfsr:'Quinn JV, et al. Ann Emerg Med. 2004;43:224–232.',
  news2:'Royal College of Physicians. National Early Warning Score (NEWS) 2. 2017.',
  qsofa:'Seymour CW, et al. JAMA. 2016;315:762–774.',
  shockIndex:'Allgöwer M, Burri C. Dtsch Med Wochenschr. 1967;92:1947–1950.',
  chadsvasc:'Lip GYH, et al. Chest. 2010;137:263–272.',
  hasbled:'Pisters R, et al. Chest. 2010;138:1093–1100.',
  air:'Andersson M, Andersson RE. World J Surg. 2008;32:1843–1849.',
  alvarado:'Alvarado A. Ann Emerg Med. 1986;15:557–564.',
  bisap:'Wu BU, et al. Gut. 2008;57:1698–1703.',
  canadianCspine:'Stiell IG, et al. JAMA. 2001;286:1841–1848.',
  nexus:'Hoffman JR, et al. N Engl J Med. 2000;343:94–99.',
  canadianHead:'Stiell IG, et al. Lancet. 2001;357:1391–1396.',
  ottawaAnkle:'Stiell IG, et al. JAMA. 1993;269:1127–1132.',
  ottawaFoot:'Stiell IG, et al. JAMA. 1993;269:1127–1132.',
  centor:'McIsaac WJ, et al. CMAJ. 1998;158:75–83.',
  gcs:'Teasdale G, Jennett B. Lancet. 1974;2:81–84.',
  correctedNa:'Katz MA. N Engl J Med. 1973;289:843–844.',
  anionGap:'Standart klinik formül: Na − (Cl + HCO₃). Albümin düzeltmesi Figge yaklaşımı.',
  correctedCa:'Standart albümin-düzeltilmiş total kalsiyum formülü.',
  osmolality:'Hesaplanan osmolalite: 2×Na + glukoz/18 + BUN/2,8.',
  qtc:'Bazett HC. Heart. 1920;7:353–370; Fridericia LS. Acta Med Scand. 1920;53:469–486.',
  ibw:'Devine BJ. Drug Intell Clin Pharm. 1974;8:650–655.',
  ventHypox:'<a href="https://academic.oup.com/ajrccm/article/209/1/24/8427573" target="_blank" rel="noopener">ATS ARDS Clinical Practice Guideline, 2024</a>; <a href="https://publications.ersnet.org/content/erj/50/2/1602426" target="_blank" rel="noopener">ERS/ATS NIV Guideline, 2017</a>; <a href="https://jts.health.mil/assets/docs/cpgs/Mechnical_Ventilation_Basics_09_Apr_2025_ID92_v1.1.pdf" target="_blank" rel="noopener">JTS Mechanical Ventilation Basics CPG, 2025</a>.',
  ventHypercap:'<a href="https://goldcopd.org/wp-content/uploads/2026/01/GOLD-Pocket-Guide-2026-v1.1-20Nov2025_WMV2.pdf" target="_blank" rel="noopener">GOLD Pocket Guide, 2026</a>; <a href="https://publications.ersnet.org/content/erj/50/2/1602426" target="_blank" rel="noopener">ERS/ATS NIV Guideline, 2017</a>; BTS/ICS Acute Hypercapnic Respiratory Failure Guideline, 2016.',
  ventTrauma:'<a href="https://jts.health.mil/assets/docs/cpgs/Mechnical_Ventilation_Basics_09_Apr_2025_ID92_v1.1.pdf" target="_blank" rel="noopener">Joint Trauma System Mechanical Ventilation Basics CPG, 2025</a>; <a href="https://braintrauma.org/coma/guidelines/severe-tbi" target="_blank" rel="noopener">Brain Trauma Foundation Severe TBI Guideline, 4th ed.</a>',
  ventPostCpr:'<a href="https://cpr.heart.org/en/resuscitation-science/cpr-and-ecc-guidelines/post-cardiac-arrest-care" target="_blank" rel="noopener">American Heart Association Post–Cardiac Arrest Care Guideline, 2025</a>.',
  ventPedsTrauma:'<a href="https://braintrauma.org/coma/guidelines/pediatric" target="_blank" rel="noopener">Brain Trauma Foundation Pediatric Severe TBI Guideline, 3rd ed.</a>; PALICC-2, 2023; PEMVECC recommendations.'
};

const scores = {
  gbs:{title:'Glasgow-Blatchford',short:'Blatchford',description:'Üst GİS kanamasında müdahale veya transfüzyon gereksinimi riskini öngörür.',sections:[
    ['Hasta bilgileri',[choice('sex','Cinsiyet',[['male','Erkek'],['female','Kadın']]),num('bun','BUN','mg/dL',0,200,.1,'Kan üre azotu'),num('hb','Hemoglobin','g/dL',1,25,.1),num('sbp','Sistolik kan basıncı','mmHg',30,300,1),num('hr','Kalp hızı','/dk',20,300,1)]],
    ['Klinik bulgular',[yes('melena','Melena'),yes('syncope','Senkop'),yes('liver','Karaciğer hastalığı'),yes('heartFailure','Kalp yetersizliği')]]
  ],calc:v=>{let s=0;const b=v.bun;if(b>=70)s+=6;else if(b>=28)s+=4;else if(b>=22.4)s+=3;else if(b>=18.2)s+=2;if(v.sex==='male'){if(v.hb<10)s+=6;else if(v.hb<12)s+=3;else if(v.hb<13)s+=1}else{if(v.hb<10)s+=6;else if(v.hb<12)s+=1}if(v.sbp<90)s+=3;else if(v.sbp<100)s+=2;else if(v.sbp<110)s+=1;if(v.hr>=100)s++;if(v.melena)s++;if(v.syncope)s+=2;if(v.liver)s+=2;if(v.heartFailure)s+=2;return s<=1?res(s,'Çok düşük risk','GBS 0–1, uygun hastada ayaktan yönetim adayı olabilir. Klinik durum ve yerel protokol ile birlikte değerlendirin.','low','Skor; endoskopi, yatış ya da taburculuk kararını tek başına belirlemez.'):res(s,'Artmış müdahale riski','Hastane temelli değerlendirme ve uygun acil yönetim gerekir. Skor yükseldikçe müdahale gereksinimi artar.',s<6?'mid':'high','Hemodinamik instabilitede skoru beklemeden resüsitasyona başlayın.')}} ,
  timi:{title:'TIMI UA/NSTEMI',short:'TIMI',description:'UA/NSTEMI’de 14 günlük ölüm, MI veya acil revaskülarizasyon riskini sınıflar.',sections:[['Her biri 1 puan',[yes('age65','Yaş ≥65'),yes('risk3','≥3 KAH risk faktörü','HT, DM, dislipidemi, aile öyküsü, aktif sigara'),yes('knownCad','Bilinen KAH','Koroner darlık ≥%50'),yes('asa','Son 7 günde ASA kullanımı'),yes('angina','Son 24 saatte ≥2 anjina atağı'),yes('st','ST deviasyonu ≥0,5 mm'),yes('marker','Pozitif kardiyak belirteç')]]],calc:v=>{const s=sumToggles(v);const risks=[4.7,4.7,8.3,13.2,19.9,26.2,40.9];return res(s,s<=2?'Düşük risk':s<=4?'Orta risk':'Yüksek risk',`Orijinal kohortta 14 günlük birleşik olay riski yaklaşık %${risks[s]}.`,s<=2?'low':s<=4?'mid':'high','Yalnız UA/NSTEMI şüphesinde ve klinik değerlendirmeyle birlikte kullanın.')}},
  heart:{title:'HEART Skoru',short:'HEART',description:'Acil serviste göğüs ağrısı olan hastalarda 6 haftalık majör kardiyak olay riskini değerlendirir.',sections:[['HEART bileşenleri',[choice('history','Öykü',[['0','Hafif şüpheli'],['1','Orta şüpheli'],['2','Çok şüpheli']]),choice('ecg','EKG',[['0','Normal'],['1','Nonspesifik repolarizasyon bozukluğu'],['2','Belirgin ST depresyonu']]),num('age','Yaş','yıl',18,120,1),choice('risk','Risk faktörleri',[['0','Yok'],['1','1–2 risk faktörü'],['2','≥3 risk faktörü / bilinen ateroskleroz']],'HT, DM, dislipidemi, obezite, sigara, aile öyküsü'),choice('troponin','Troponin',[['0','≤ normal sınır'],['1','Normal sınırın 1–3 katı'],['2','>3 katı']],'Kullandığınız testin üst referans sınırına göre')]]],calc:v=>{const s=+v.history + +v.ecg + (v.age>=65?2:v.age>=45?1:0) + +v.risk + +v.troponin;return s<=3?res(s,'Düşük risk','6 haftalık MACE riski yaklaşık %1,7. Uygun seri troponin algoritması ve klinik değerlendirme gereklidir.','low'):s<=6?res(s,'Orta risk','6 haftalık MACE riski yaklaşık %16,6. Gözlem ve ileri değerlendirme düşünülür.','mid'):res(s,'Yüksek risk','6 haftalık MACE riski yaklaşık %50,1. Erken invaziv değerlendirme gündeme gelir.','high','HEART, akut göğüs ağrısı değerlendirmesinin tamamlayıcısıdır.')}},
  grace:{title:'GRACE',short:'GRACE',description:'Akut koroner sendromda hastane içi mortalite riskini GRACE 1.0 kabul puanıyla sınıflar.',sections:[['Başvuru verileri',[num('age','Yaş','yıl',18,120,1),num('hr','Kalp hızı','/dk',20,300,1),num('sbp','Sistolik kan basıncı','mmHg',30,300,1),num('creat','Kreatinin','mg/dL',.1,15,.1),choice('killip','Killip sınıfı',[['1','I — Kalp yetersizliği yok'],['2','II — Raller / S3 / JVD'],['3','III — Pulmoner ödem'],['4','IV — Kardiyojenik şok']])]],['Ek bulgular',[yes('arrest','Başvuruda kardiyak arrest'),yes('st','ST segment deviasyonu'),yes('marker','Yüksek kardiyak belirteç')]]],calc:v=>{let s=band(v.age,[[30,0],[40,8],[50,25],[60,41],[70,58],[80,75],[90,91],[Infinity,100]]);s+=band(v.hr,[[50,0],[70,3],[90,9],[110,15],[150,24],[200,38],[Infinity,46]]);s+=band(v.sbp,[[80,58],[100,46],[120,36],[140,26],[160,18],[180,10],[200,4],[Infinity,0]]);s+=band(v.creat,[[.4,1],[.8,4],[1.2,7],[1.6,10],[2,13],[4,21],[Infinity,28]]);s+=({1:0,2:20,3:39,4:59})[v.killip];if(v.arrest)s+=39;if(v.st)s+=28;if(v.marker)s+=14;return s<=108?res(s,'Düşük hastane içi risk','GRACE ≤108: hastane içi mortalite için düşük risk sınıfı (<%1).','low'):s<=140?res(s,'Orta hastane içi risk','GRACE 109–140: orta risk sınıfı (yaklaşık %1–3).','mid'):res(s,'Yüksek hastane içi risk','GRACE >140: yüksek risk sınıfı (>%3); erken invaziv strateji açısından önemlidir.','high','Bu araç GRACE 1.0 kabul puanını ve risk sınıfını verir; GRACE 2.0 yüzdesi değildir.')}},
  abcd2:{title:'ABCD²',short:'ABCD²',description:'TİA sonrası 2 günlük erken inme riskini tahmin eder.',sections:[['Klinik bilgiler',[num('age','Yaş','yıl',18,120,1),num('sbp','Sistolik kan basıncı','mmHg',50,300,1),num('dbp','Diyastolik kan basıncı','mmHg',20,200,1),choice('clinical','Klinik özellik',[['2','Tek taraflı güçsüzlük'],['1','Güçsüzlük olmadan konuşma bozukluğu'],['0','Diğer']]),choice('duration','Semptom süresi',[['2','≥60 dakika'],['1','10–59 dakika'],['0','<10 dakika']]),yes('diabetes','Diyabetes mellitus')]]],calc:v=>{const s=(v.age>=60?1:0)+((v.sbp>=140||v.dbp>=90)?1:0)+ +v.clinical + +v.duration +(v.diabetes?1:0);return s<=3?res(s,'Düşük risk','Orijinal doğrulamada 2 günlük inme riski yaklaşık %1,0.','low'):s<=5?res(s,'Orta risk','Orijinal doğrulamada 2 günlük inme riski yaklaşık %4,1.','mid'):res(s,'Yüksek risk','Orijinal doğrulamada 2 günlük inme riski yaklaşık %8,1.','high','ABCD², vasküler görüntüleme ve uzman değerlendirmesinin yerine geçmez; düşük skor güvenli taburculuk anlamına gelmez.')}},
  curb65:{title:'CURB-65',short:'CURB-65',description:'Toplum kökenli pnömonide 30 günlük mortalite riskini sınıflar.',sections:[['Başvuru verileri',[yes('confusion','Yeni konfüzyon'),num('bun','BUN','mg/dL',0,200,.1,'>19 mg/dL ise 1 puan'),num('rr','Solunum sayısı','/dk',5,80,1),num('sbp','Sistolik kan basıncı','mmHg',30,300,1),num('dbp','Diyastolik kan basıncı','mmHg',20,200,1),num('age','Yaş','yıl',18,120,1)]]],calc:v=>{const s=(v.confusion?1:0)+(v.bun>19?1:0)+(v.rr>=30?1:0)+((v.sbp<90||v.dbp<=60)?1:0)+(v.age>=65?1:0);const mortality=[.7,3.2,3,17,41.5,57][s];return s<=1?res(s,'Düşük risk',`Orijinal çalışmada 30 günlük mortalite yaklaşık %${mortality}. Ayaktan tedavi uygunluğu klinikle belirlenir.`,'low'):s===2?res(s,'Orta risk',`Orijinal çalışmada 30 günlük mortalite yaklaşık %${mortality}. Kısa yatış / hastane gözetimi düşünülür.`,'mid'):res(s,'Yüksek risk',`Orijinal çalışmada 30 günlük mortalite yaklaşık %${mortality}. Yatış ve özellikle ≥4 puanda yoğun bakım değerlendirmesi düşünülür.`,'high','Oksijenasyon ve IDSA/ATS ağır pnömoni ölçütleri ayrıca değerlendirilmelidir.')}},
  psi:{title:'PSI / PORT',short:'PSI',description:'Toplum kökenli pnömonide 30 günlük mortaliteyi 20 değişkenle sınıflar.',sections:[['Demografi',[choice('sex','Cinsiyet',[['male','Erkek'],['female','Kadın']]),num('age','Yaş','yıl',18,120,1),yes('nursing','Bakımevinde yaşama')]],['Komorbidite',[yes('cancer','Neoplastik hastalık'),yes('liver','Karaciğer hastalığı'),yes('chf','Kalp yetersizliği'),yes('cvd','Serebrovasküler hastalık'),yes('renal','Böbrek hastalığı')]],['Fizik muayene',[yes('mental','Bilinç değişikliği'),num('hr','Kalp hızı','/dk',20,300,1),num('rr','Solunum sayısı','/dk',5,80,1),num('sbp','Sistolik kan basıncı','mmHg',30,300,1),num('temp','Vücut sıcaklığı','°C',25,45,.1)]],['Laboratuvar ve görüntüleme — ölçülmediyse boş bırakın',[num('ph','Arteriyel pH','',6.5,8,.01,'Ölçülmediyse boş bırakın',false),num('bun','BUN','mg/dL',0,200,.1,'Ölçülmediyse boş bırakın',false),num('na','Sodyum','mmol/L',80,200,1,'Ölçülmediyse boş bırakın',false),num('glucose','Glukoz','mg/dL',10,1000,1,'Ölçülmediyse boş bırakın',false),num('hct','Hematokrit','%',5,70,.1,'Ölçülmediyse boş bırakın',false),num('pao2','PaO₂','mmHg',20,700,1,'Oda havasında; ölçülmediyse boş bırakın',false),yes('hypoxemia','SpO₂ <%90','PaO₂ girilmediyse kullanılabilir'),yes('effusion','Plevral efüzyon')]]],calc:v=>{const step1=v.age<50&&!v.cancer&&!v.liver&&!v.chf&&!v.cvd&&!v.renal&&!v.mental&&v.hr<125&&v.rr<30&&v.sbp>=90&&v.temp>=35&&v.temp<40;if(step1)return res('I','Risk sınıfı I','30 günlük mortalite yaklaşık %0,1; ayaktan tedavi adayı olabilir.','low','Sosyal durum, oral alım, oksijenasyon ve klinik yargı ayrıca değerlendirilir.');let s=v.age-(v.sex==='female'?10:0)+(v.nursing?10:0)+(v.cancer?30:0)+(v.liver?20:0)+(v.chf?10:0)+(v.cvd?10:0)+(v.renal?10:0)+(v.mental?20:0)+(v.hr>=125?10:0)+(v.rr>=30?20:0)+(v.sbp<90?20:0)+((v.temp<35||v.temp>=40)?15:0)+((v.ph!=null&&v.ph<7.35)?30:0)+((v.bun!=null&&v.bun>=30)?20:0)+((v.na!=null&&v.na<130)?20:0)+((v.glucose!=null&&v.glucose>=250)?10:0)+((v.hct!=null&&v.hct<30)?10:0)+(((v.pao2!=null&&v.pao2<60)||v.hypoxemia)?10:0)+(v.effusion?10:0);const cls=s<=70?'II':s<=90?'III':s<=130?'IV':'V';const data={II:['%0,6','Ayaktan tedavi adayı','low'],III:['%0,9','Kısa gözlem / ayaktan tedavi düşünülebilir','low'],IV:['%9,3','Yatarak tedavi genellikle uygundur','mid'],V:['%27,0','Yatarak tedavi; yoğun bakım gereksinimini ayrıca değerlendir','high']}[cls];return res(`${s} · ${cls}`,`Risk sınıfı ${cls}`,`30 günlük mortalite yaklaşık ${data[0]}. ${data[1]}.`,data[2],'Eksik laboratuvar değişkenleri 0 puan kabul edilmiştir. PSI, yoğun bakım gereksinimini tek başına belirlemez.')}},
  wellsDvt:{title:'Wells DVT',short:'Wells DVT',description:'DVT için değiştirilmiş iki düzeyli klinik ön test olasılığı.',sections:[['Klinik ölçütler',[yes('cancer','Aktif kanser','Son 6 ay tedavi veya palyatif'),yes('paralysis','Paralizi / parezi / alt ekstremite alçısı'),yes('bed','≥3 gün yatak istirahati veya son 12 haftada büyük cerrahi'),yes('tender','Derin ven trasesinde lokal hassasiyet'),yes('leg','Tüm bacakta şişlik'),yes('calf','Baldır çevresi farkı ≥3 cm'),yes('edema','Semptomatik bacakta gode bırakan ödem'),yes('collateral','Kollateral yüzeyel venler','Variköz olmayan'),yes('previous','Önceki DVT'),yes('alternative','Alternatif tanı en az DVT kadar olası','−2 puan',-2)]]],calc:v=>{let s=0;for(const [k,val] of Object.entries(v))if(val)s+=k==='alternative'?-2:1;return s>=2?res(s,'DVT olası','İki düzeyli Wells modelinde skor ≥2: DVT olası. Uygun görüntüleme / D-dimer algoritmasını izleyin.','high'):res(s,'DVT olası değil','İki düzeyli Wells modelinde skor <2: DVT olası değil. Uygun hastada D-dimer ile dışlama yolu kullanılabilir.','low','Antikoagülasyon ve görüntüleme kararı yerel tanı algoritmasına göre verilmelidir.')}},
  wellsPe:{title:'Wells PE',short:'Wells PE',description:'Pulmoner emboli için klinik ön test olasılığı.',sections:[['Klinik ölçütler',[yes('dvt','DVT klinik bulguları','Bacak şişliği ve derin ven palpasyonunda ağrı',3),yes('alternative','PE alternatif tanıdan daha olası','Klinisyen değerlendirmesi',3),yes('hr','Kalp hızı >100/dk','',1.5),yes('immobilization','Son 4 haftada ≥3 gün immobilizasyon veya cerrahi','',1.5),yes('previous','Önceki DVT / PE','',1.5),yes('hemoptysis','Hemoptizi','',1),yes('cancer','Aktif malignite','Tedavi sürüyor, son 6 ay tedavi veya palyatif',1)]]],calc:v=>{let s=0;const pts={dvt:3,alternative:3,hr:1.5,immobilization:1.5,previous:1.5,hemoptysis:1,cancer:1};Object.keys(pts).forEach(k=>{if(v[k])s+=pts[k]});return s>4?res(s,'PE olası','İki düzeyli Wells modelinde skor >4: PE olası. Görüntüleme temelli tanı yolu uygundur.','high'):res(s,'PE olası değil','İki düzeyli Wells modelinde skor ≤4: PE olası değil. Uygun hastada D-dimer / PERC temelli dışlama yolu düşünülebilir.','low','Hemodinamik instabil PE şüphesinde standart stabil hasta algoritması uygulanmaz.')}},
  perc:{title:'PERC',short:'PERC',description:'Klinik olarak düşük riskli hastada PE’yi ek test olmadan dışlama ölçütleri.',sections:[['Ön koşul',[choice('lowRisk','Klinik gestalt ile PE olasılığı düşük mü?',[['yes','Evet — <%15'],['no','Hayır / emin değilim']],'PERC yalnız düşük ön test olasılığında uygulanır.')]],['Pozitif PERC ölçütleri',[yes('age','Yaş ≥50'),yes('hr','Kalp hızı ≥100/dk'),yes('sat','Oda havasında SpO₂ <%95'),yes('leg','Tek taraflı bacak şişliği'),yes('hemoptysis','Hemoptizi'),yes('estrogen','Ekzojen östrojen / hormon kullanımı'),yes('previous','Önceki DVT veya PE'),yes('surgery','Son 4 haftada hastaneye yatış gerektiren cerrahi veya travma')]]],calc:v=>{const s=['age','hr','sat','leg','hemoptysis','estrogen','previous','surgery'].filter(k=>v[k]).length;if(v.lowRisk!=='yes')return res(s,'PERC uygulanamaz','Ön test olasılığı düşük değilse PERC ile PE dışlanamaz. Wells/Geneva ve uygun tanı algoritmasını kullanın.','high','PERC, yalnız klinik gestalt ile düşük riskli erişkin hastalarda kullanılır.');return s===0?res(0,'PERC negatif','Sekiz ölçütün tamamı negatif. Düşük klinik olasılıkla birlikte PE ek test yapılmadan dışlanabilir.','low','Hemodinamik instabilite, gebelik veya PERC’nin doğrulanmadığı özel popülasyonlarda kullanmayın.'):res(s,'PERC pozitif','En az bir PERC ölçütü pozitif; PERC ile PE dışlanamaz. Uygun hastada D-dimer veya görüntüleme algoritmasına ilerleyin.','mid','PERC pozitifliği PE tanısı anlamına gelmez.')}},
  spesi:{title:'sPESI',short:'sPESI',description:'Doğrulanmış PE’de 30 günlük mortalite riskini sınıflar.',sections:[['Her biri 1 puan',[yes('age','Yaş >80'),yes('cancer','Kanser öyküsü'),yes('cardiopulm','Kronik kardiyopulmoner hastalık','Kalp yetersizliği veya kronik akciğer hastalığı'),yes('hr','Kalp hızı ≥110/dk'),yes('sbp','Sistolik KB <100 mmHg'),yes('sat','SpO₂ <%90')]]],calc:v=>{const s=sumToggles(v);return s===0?res(0,'Düşük risk','sPESI 0: doğrulanmış PE’de düşük 30 günlük mortalite riski. Ayaktan tedavi uygunluğu ayrıca değerlendirilmelidir.','low'):res(s,'Yüksek risk','sPESI ≥1: artmış 30 günlük mortalite riski; hastane temelli değerlendirme gerekir.','high','sPESI tanı aracı değildir ve tek başına taburculuk kararı verdirmez.')}},
  hestia:{title:'Hestia Kriterleri',short:'Hestia',description:'Doğrulanmış PE’de ayaktan tedaviye engel ölçütleri tarar.',sections:[['Dışlama ölçütleri',[yes('unstable','Hemodinamik instabilite','Sistolik KB <100 mmHg ve nabız >100, yoğun bakım gereksinimi veya klinik yargı'),yes('reperfusion','Tromboliz veya embolektomi gereksinimi'),yes('bleeding','Aktif kanama veya yüksek kanama riski'),yes('oxygen','>24 saat oksijen gereksinimi'),yes('anticoag','PE, antikoagülan tedavi sırasında gelişti'),yes('pain','>24 saat IV analjezi gerektiren şiddetli ağrı'),yes('medical','>24 saat yatış gerektiren tıbbi veya sosyal neden'),yes('renal','Kreatinin klirensi <30 mL/dk'),yes('liver','Ağır karaciğer yetersizliği'),yes('pregnancy','Gebelik'),yes('hit','Heparine bağlı trombositopeni öyküsü')]]],calc:v=>{const s=sumToggles(v);return s===0?res(0,'Ayaktan tedavi adayı olabilir','Hestia dışlama ölçütü yok. Uygun takip, tedavi erişimi ve klinik değerlendirmeyle evde tedavi düşünülebilir.','low'):res(s,'Ayaktan tedaviye uygun değil',`${s} Hestia dışlama ölçütü mevcut; hastane temelli tedavi/değerlendirme gerekir.`,'high','Hestia yalnız doğrulanmış akut PE için kullanılır.')}},
  news2:{title:'NEWS2',short:'NEWS2',description:'Akut hastalıkta fizyolojik kötüleşmeyi yedi parametreyle değerlendirir.',sections:[['Solunum',[num('rr','Solunum sayısı','/dk',3,80,1),choice('spo2Scale','SpO₂ ölçeği',[['1','Ölçek 1 — standart'],['2','Ölçek 2 — doğrulanmış hiperkapnik solunum yetmezliği']]),num('sat','SpO₂','%',40,100,1),yes('oxygen','Ek oksijen alıyor')]],['Dolaşım ve diğer',[num('sbp','Sistolik kan basıncı','mmHg',40,300,1),num('hr','Kalp hızı','/dk',20,250,1),num('temp','Sıcaklık','°C',25,45,.1),choice('conscious','Bilinç',[['0','Alert'],['3','Yeni konfüzyon / V-P-U']])]]],calc:v=>{const component=[];component.push(v.rr<=8?3:v.rr<=11?1:v.rr<=20?0:v.rr<=24?2:3);let os=0;if(v.spo2Scale==='1')os=v.sat<=91?3:v.sat<=93?2:v.sat<=95?1:0;else if(v.sat<=83)os=3;else if(v.sat<=85)os=2;else if(v.sat<=87)os=1;else if(v.sat<=92)os=0;else if(!v.oxygen)os=0;else os=v.sat<=94?1:v.sat<=96?2:3;component.push(os);component.push(v.oxygen?2:0);component.push(v.sbp<=90?3:v.sbp<=100?2:v.sbp<=110?1:v.sbp<=219?0:3);component.push(v.hr<=40?3:v.hr<=50?1:v.hr<=90?0:v.hr<=110?1:v.hr<=130?2:3);component.push(v.temp<=35?3:v.temp<=36?1:v.temp<=38?0:v.temp<=39?1:2);component.push(+v.conscious);const s=component.reduce((a,b)=>a+b,0),single3=component.some(x=>x===3);return s>=7?res(s,'Yüksek klinik risk','Acil/erken yanıt, sürekli monitorizasyon ve üst düzey klinik değerlendirme gerekir.','high'):s>=5?res(s,'Orta klinik risk','Acil klinik değerlendirme ve sık monitorizasyon gerekir.','mid'):single3?res(s,'Tek parametrede ciddi sapma','Toplam düşük olsa da bir parametre 3 puan; klinik değerlendirme ve daha sık izlem gerekir.','mid'):res(s,'Düşük klinik risk','Rutin NEWS2 izlem sıklığı ve klinik değerlendirme uygundur.','low','NEWS2 tanı koymaz; klinik kötüleşmede skordan bağımsız acil değerlendirme yapılır.')}},
  qsofa:{title:'qSOFA',short:'qSOFA',description:'Enfeksiyon şüphesinde kötü sonlanım riski için hızlı tarama.',sections:[['Ölçütler',[yes('rr','Solunum sayısı ≥22/dk'),yes('mental','Bilinç değişikliği','GKS <15'),yes('sbp','Sistolik KB ≤100 mmHg')]]],calc:v=>{const s=sumToggles(v);return s>=2?res(s,'Artmış kötü sonlanım riski','qSOFA ≥2; organ disfonksiyonu açısından ileri değerlendirme ve yakın izlem gerekir.','high'):res(s,'qSOFA <2','Yüksek risk eşiği karşılanmıyor; ancak sepsis dışlanamaz.','low','qSOFA bir sepsis tanı veya dışlama testi değildir.')}},
  shockIndex:{title:'Şok İndeksi',short:'Şok indeksi',description:'Kalp hızının sistolik kan basıncına oranını hesaplar.',sections:[['Vital bulgular',[num('hr','Kalp hızı','/dk',20,300,1),num('sbp','Sistolik kan basıncı','mmHg',30,300,1)]]],calc:v=>{const s=v.hr/v.sbp,display=s.toFixed(2);return s>=1?res(display,'Belirgin yüksek','Şok indeksi ≥1,0: ciddi dolaşım bozukluğu açısından yüksek risk.','high'):s>=.9?res(display,'Yüksek','Şok indeksi ≥0,9: gizli hipoperfüzyon olasılığı açısından dikkat.','mid'):res(display,'Referans aralıkta','Şok indeksi <0,9. Tek başına normal sonuç şoku dışlamaz.','low','Yaş, ilaçlar, gebelik ve ritim bozuklukları yorumu etkileyebilir.')}},
  chadsvasc:{title:'CHA₂DS₂-VASc',short:'CHA₂DS₂-VASc',description:'Nonvalvüler AF’de tromboembolik inme riskini değerlendirir.',sections:[['Risk faktörleri',[yes('chf','Kalp yetersizliği / LV sistolik disfonksiyon'),yes('ht','Hipertansiyon'),choice('age','Yaş',[['0','<65'],['1','65–74'],['2','≥75']]),yes('dm','Diyabetes mellitus'),yes('stroke','İnme / TİA / sistemik emboli öyküsü','2 puan',2),yes('vascular','Vasküler hastalık','MI, periferik arter hastalığı veya aort plağı'),yes('female','Kadın cinsiyet')]]],calc:v=>{const s=(v.chf?1:0)+(v.ht?1:0)+(+v.age)+(v.dm?1:0)+(v.stroke?2:0)+(v.vascular?1:0)+(v.female?1:0);const sexOnly=v.female&&s===1;return (s===0||sexOnly)?res(s,'Düşük tromboemboli riski','Kadın cinsiyet tek başına risk değiştiricidir; ek risk faktörü yoksa düşük risk kabul edilir.','low'):res(s,s>=2?'Artmış tromboemboli riski':'Ara risk','Antikoagülasyon kararı güncel AF kılavuzu, cinsiyet ve hasta tercihleriyle birlikte verilmelidir.',s>=2?'high':'mid','Mekanik kapak veya orta-ağır mitral darlığında bu skor kullanılmaz.')}},
  hasbled:{title:'HAS-BLED',short:'HAS-BLED',description:'AF’de antikoagülasyon sırasında değiştirilebilir kanama risklerini belirler.',sections:[['Risk faktörleri',[yes('ht','Kontrolsüz hipertansiyon','Sistolik KB >160 mmHg'),yes('renal','Anormal böbrek fonksiyonu'),yes('liver','Anormal karaciğer fonksiyonu'),yes('stroke','İnme öyküsü'),yes('bleeding','Majör kanama öyküsü / yatkınlık'),yes('inr','Labil INR','TTR düşük veya instabil/yüksek INR'),yes('elderly','Yaş >65'),yes('drugs','Kanamayı artıran ilaç','Antiplatelet veya NSAİİ'),yes('alcohol','Aşırı alkol kullanımı')]]],calc:v=>{const s=sumToggles(v);return s>=3?res(s,'Yüksek kanama riski','HAS-BLED ≥3: daha sık kontrol ve değiştirilebilir risklerin düzeltilmesi gerekir.','high'):res(s,'Düşük–orta kanama riski','Değiştirilebilir risk faktörlerini düzeltin ve periyodik yeniden değerlendirin.',s===2?'mid':'low','Yüksek HAS-BLED antikoagülasyonu otomatik olarak reddetme gerekçesi değildir.')}},
  air:{title:'AIR Skoru',short:'AIR',description:'Akut apandisit olasılığını klinik ve inflamatuvar bulgularla sınıflar.',sections:[['Klinik',[yes('vomiting','Kusma'),yes('rlq','Sağ alt kadran ağrısı'),choice('guarding','Rebound veya musküler defans',[['0','Yok'],['1','Hafif'],['2','Orta'],['3','Güçlü']]),yes('fever','Ateş ≥38,5 °C')]],['Laboratuvar',[choice('wbc','Lökosit',[['0','<10 ×10⁹/L'],['1','10–14,9 ×10⁹/L'],['2','≥15 ×10⁹/L']]),choice('neut','Nötrofil oranı',[['0','<%70'],['1','%70–84'],['2','≥%85']]),choice('crp','CRP',[['0','<10 mg/L'],['1','10–49 mg/L'],['2','≥50 mg/L']])]]],calc:v=>{const s=(v.vomiting?1:0)+(v.rlq?1:0)+(+v.guarding)+(v.fever?1:0)+(+v.wbc)+(+v.neut)+(+v.crp);return s<=4?res(s,'Düşük olasılık','AIR 0–4: düşük apandisit olasılığı; klinik yeniden değerlendirme önemlidir.','low'):s<=8?res(s,'Ara olasılık','AIR 5–8: gözlem, seri muayene ve/veya görüntüleme düşünülür.','mid'):res(s,'Yüksek olasılık','AIR 9–12: yüksek apandisit olasılığı; cerrahi değerlendirme gerekir.','high','Skor tek başına ameliyat kararı verdirmez.')}},
  alvarado:{title:'Alvarado',short:'Alvarado',description:'Şüpheli akut apandisitte 10 puanlı MANTRELS skoru.',sections:[['Semptom ve bulgular',[yes('migration','Ağrının sağ alt kadrana göçü'),yes('anorexia','İştahsızlık'),yes('nausea','Bulantı veya kusma'),yes('tender','Sağ alt kadran hassasiyeti','2 puan',2),yes('rebound','Rebound hassasiyet'),yes('fever','Ateş ≥37,3 °C')]],['Laboratuvar',[yes('wbc','Lökositoz >10 ×10⁹/L','2 puan',2),yes('shift','Sola kayma / nötrofili')]]],calc:v=>{const s=(v.migration?1:0)+(v.anorexia?1:0)+(v.nausea?1:0)+(v.tender?2:0)+(v.rebound?1:0)+(v.fever?1:0)+(v.wbc?2:0)+(v.shift?1:0);return s<=4?res(s,'Düşük olasılık','Alvarado 0–4: apandisit olasılığı düşük. Klinik izlem ve alternatif tanılar değerlendirilir.','low'):s<=6?res(s,'Ara olasılık','Alvarado 5–6: apandisit ile uyumlu; gözlem ve görüntüleme düşünülür.','mid'):res(s,'Yüksek olasılık','Alvarado ≥7: yüksek apandisit olasılığı; cerrahi değerlendirme/görüntüleme gerekir.','high','Kadınlarda ve özel popülasyonlarda performans değişebilir.')}},
  bisap:{title:'BISAP',short:'BISAP',description:'Akut pankreatitte ilk 24 saatte mortalite ve ağır hastalık riskini değerlendirir.',sections:[['İlk 24 saat',[yes('bun','BUN >25 mg/dL'),yes('mental','Bilinç bozukluğu','GKS <15'),yes('sirs','SIRS ≥2 kriter'),yes('age','Yaş >60'),yes('effusion','Plevral efüzyon')]]],calc:v=>{const s=sumToggles(v);return s>=3?res(s,'Yüksek risk','BISAP ≥3: ağır akut pankreatit ve mortalite riski artmıştır; yakın izlem gerekir.','high'):res(s,'Daha düşük risk','BISAP 0–2: daha düşük risk; seri klinik değerlendirme sürdürülmelidir.',s===2?'mid':'low','BISAP ilk 24 saat verileriyle kullanılır ve organ yetmezliği değerlendirmesinin yerine geçmez.')}},
  canadianCspine:{title:'Canadian C-Spine Rule',short:'Canadian C-Spine',description:'Alert ve stabil künt travma hastasında servikal görüntüleme gereksinimini değerlendirir.',sections:[['Uygunluk',[choice('eligible','Hasta alert (GKS 15), stabil ve ≥16 yaş mı?',[['yes','Evet'],['no','Hayır']])]],['Yüksek risk',[yes('age','Yaş ≥65'),yes('danger','Tehlikeli mekanizma','≥90 cm/5 basamak düşme, aksiyel yük, yüksek hızlı/rollover/ejection MVC, motorlu eğlence aracı veya bisiklet çarpışması'),yes('paresthesia','Ekstremite parestezisi')]],['Düşük risk ve hareket',[yes('rearend','Basit arkadan çarpışmalı MVC'),yes('sitting','Acil serviste oturur pozisyonda'),yes('ambulatory','Herhangi bir zamanda yürüyebildi'),yes('delayed','Boyun ağrısı gecikmeli başladı'),yes('noMidline','Orta hat servikal hassasiyet yok'),yes('rotate','Boynunu sağa ve sola 45° aktif çevirebiliyor')]]],calc:v=>{if(v.eligible!=='yes')return res('—','Kural uygulanamaz','Hasta Canadian C-Spine Rule’un doğrulandığı alert ve stabil erişkin popülasyona uymuyor.','high');if(v.age||v.danger||v.paresthesia)return res('Pozitif','Servikal görüntüleme gerekli','En az bir yüksek risk ölçütü mevcut.','high');const low=v.rearend||v.sitting||v.ambulatory||v.delayed||v.noMidline;if(!low)return res('Pozitif','Servikal görüntüleme gerekli','Aktif hareket değerlendirmesine izin veren düşük risk özelliği yok.','high');return v.rotate?res('Negatif','Klinik olarak temizlenebilir','Düşük risk özelliği var ve hasta boynunu iki yana 45° çevirebiliyor.','low'):res('Pozitif','Servikal görüntüleme gerekli','Hasta boynunu iki yana 45° aktif çeviremiyor.','high','Nörolojik kötüleşme veya klinik kaygıda kuraldan bağımsız görüntüleme yapılır.')}},
  nexus:{title:'NEXUS C-Spine',short:'NEXUS',description:'Künt travmada düşük riskli hastayı servikal görüntüleme olmadan ayırır.',sections:[['Pozitif ölçütler',[yes('tender','Posterior orta hat servikal hassasiyet'),yes('neuro','Fokal nörolojik defisit'),yes('alert','Bilinç düzeyinde bozukluk'),yes('intox','İntoksikasyon bulgusu'),yes('distracting','Ağrılı dikkat dağıtıcı yaralanma')]]],calc:v=>{const s=sumToggles(v);return s===0?res(0,'NEXUS negatif','Beş düşük risk koşulu karşılanıyor; uygun hastada servikal görüntüleme gerekmeyebilir.','low'):res(s,'NEXUS pozitif','En az bir kriter mevcut; servikal omurga klinik olarak temizlenemez.','high','Kural künt travma için geliştirilmiştir; klinik yargı önceliklidir.')}},
  canadianHead:{title:'Canadian CT Head Rule',short:'Canadian CT Head',description:'Minör kafa travmasında kraniyal BT gereksinimini değerlendirir.',sections:[['Uygunluk',[choice('eligible','GKS 13–15 ve bilinç kaybı, amnezi veya dezoryantasyon var mı?',[['yes','Evet'],['no','Hayır']]),yes('excluded','Dışlama ölçütü var','Yaş <16, antikoagülan/kanama bozukluğu, açık kafa travması veya travma sonrası nöbet')]],['Yüksek risk',[yes('gcs','Yaralanmadan 2 saat sonra GKS <15'),yes('open','Açık/deprese kafatası kırığı şüphesi'),yes('basal','Bazal kafatası kırığı bulgusu'),yes('vomit','≥2 kusma epizodu'),yes('age','Yaş ≥65')]],['Orta risk',[yes('amnesia','Çarpma öncesi amnezi ≥30 dk'),yes('danger','Tehlikeli mekanizma','Yaya çarpması, araçtan fırlama veya ≥90 cm/5 basamak düşme')]]],calc:v=>{if(v.eligible!=='yes'||v.excluded)return res('—','Kural uygulanamaz','Hasta Canadian CT Head Rule’un dahil edilme koşullarını karşılamıyor veya dışlama ölçütü mevcut.','high');const high=['gcs','open','basal','vomit','age'].some(k=>v[k]),medium=v.amnesia||v.danger;if(high)return res('Yüksek risk','Kraniyal BT gerekli','Nöroşirürjik girişim açısından yüksek risk ölçütü mevcut.','high');if(medium)return res('Orta risk','Kraniyal BT gerekli','BT’de klinik önemli beyin hasarı açısından orta risk ölçütü mevcut.','mid');return res('Negatif','Kural BT gerekliliğini desteklemiyor','Uygun popülasyonda Canadian CT Head Rule ölçütü yok.','low','Klinik kötüleşmede veya yeni nörolojik bulguda yeniden değerlendirin.')}},
  ottawaAnkle:{title:'Ottawa Ayak Bileği Kuralı',short:'Ottawa ayak bileği',description:'Akut ayak bileği travmasında ayak bileği grafisi gereksinimi.',sections:[['Uygunluk ve bulgular',[choice('pain','Malleoler bölgede ağrı var mı?',[['yes','Evet'],['no','Hayır']]),yes('lateral','Lateral malleol posterior kenarı/ucunda kemik hassasiyeti'),yes('medial','Medial malleol posterior kenarı/ucunda kemik hassasiyeti'),yes('weight','Yaralanmadan hemen sonra ve acilde 4 adım basamama')]]],calc:v=>{if(v.pain!=='yes')return res('—','Kural uygulanamaz','Malleoler bölgede ağrı yok; Ottawa ayak bileği kuralı bu bölüm için uygulanmaz.','mid');return (v.lateral||v.medial||v.weight)?res('Pozitif','Ayak bileği grafisi gerekli','En az bir Ottawa ayak bileği ölçütü mevcut.','high'):res('Negatif','Grafi gerekmeyebilir','Uygun hastada ayak bileği kırığı klinik olarak dışlanabilir.','low','Gebelik, belirgin duyu kusuru veya güvenilir muayene yapılamayan hastada klinik yargı kullanın.')}},
  ottawaFoot:{title:'Ottawa Ayak Kuralı',short:'Ottawa ayak',description:'Akut orta ayak travmasında ayak grafisi gereksinimi.',sections:[['Uygunluk ve bulgular',[choice('pain','Orta ayak bölgesinde ağrı var mı?',[['yes','Evet'],['no','Hayır']]),yes('fifth','5. metatars tabanında kemik hassasiyeti'),yes('navicular','Naviküler kemikte hassasiyet'),yes('weight','Yaralanmadan hemen sonra ve acilde 4 adım basamama')]]],calc:v=>{if(v.pain!=='yes')return res('—','Kural uygulanamaz','Orta ayak bölgesinde ağrı yok; Ottawa ayak kuralı bu bölüm için uygulanmaz.','mid');return (v.fifth||v.navicular||v.weight)?res('Pozitif','Ayak grafisi gerekli','En az bir Ottawa orta ayak ölçütü mevcut.','high'):res('Negatif','Grafi gerekmeyebilir','Uygun hastada orta ayak kırığı klinik olarak dışlanabilir.','low','Lisfranc yaralanması şüphesinde kural negatif olsa bile ileri değerlendirme gerekir.')}},
  centor:{title:'Modifiye Centor / McIsaac',short:'Centor',description:'Akut farenjitte Grup A streptokok olasılığını sınıflar.',sections:[['Kriterler',[yes('fever','Ateş >38 °C'),yes('exudate','Tonsiller eksüda veya şişlik'),yes('nodes','Hassas anterior servikal lenfadenopati'),yes('noCough','Öksürük yok'),choice('age','Yaş',[['1','3–14'],['0','15–44'],['-1','≥45']])]]],calc:v=>{const s=(v.fever?1:0)+(v.exudate?1:0)+(v.nodes?1:0)+(v.noCough?1:0)+(+v.age);return s<=1?res(s,'Düşük GAS olasılığı','Genellikle streptokok testi veya antibiyotik gerekmez; klinik bağlamı değerlendirin.','low'):s<=3?res(s,'Orta GAS olasılığı','Hızlı antijen testi veya boğaz kültürü düşünülür; pozitifse tedavi edilir.','mid'):res(s,'Yüksek GAS olasılığı','Mikrobiyolojik doğrulama ve yerel kılavuza göre tedavi yaklaşımı uygundur.','high','Viral bulgular belirginse skor kullanılmamalı; antibiyotik kararı yerel direnç ve kılavuza göre verilmelidir.')}},
  gcs:{title:'Glasgow Koma Skalası',short:'GKS',description:'En iyi göz, sözel ve motor yanıtı ayrı ayrı puanlar.',sections:[['Yanıtlar',[choice('eye','Göz açma',[['4','Spontan'],['3','Sese'],['2','Basınca/ağrıya'],['1','Yok']]),choice('verbal','Sözel yanıt',[['5','Oryante'],['4','Konfüze'],['3','Uygunsuz kelimeler'],['2','Anlaşılmaz sesler'],['1','Yok'],['1t','Entübe — 1T']]),choice('motor','Motor yanıt',[['6','Emirlere uyar'],['5','Ağrıyı lokalize eder'],['4','Normal fleksiyon / geri çeker'],['3','Anormal fleksiyon'],['2','Ekstansiyon'],['1','Yok']])]]],calc:v=>{const s=(+v.eye)+parseInt(v.verbal,10)+(+v.motor),tag=v.verbal==='1t'?`${s}T`:s;return s<=8?res(tag,'Ağır bilinç bozukluğu',`GKS ${tag} (E${v.eye} V${v.verbal==='1t'?'1T':v.verbal} M${v.motor}). Havayolu ve nörolojik acil değerlendirme gerekir.`,'high'):s<=12?res(tag,'Orta bilinç bozukluğu',`GKS ${tag} (E${v.eye} V${v.verbal==='1t'?'1T':v.verbal} M${v.motor}). Yakın izlem ve seri değerlendirme gerekir.`,'mid'):res(tag,'Hafif / normal aralık',`GKS ${tag} (E${v.eye} V${v.verbal==='1t'?'1T':v.verbal} M${v.motor}). Klinik bağlam ve önceki GKS ile karşılaştırın.`,'low','Toplam puanla birlikte E/V/M bileşenlerini mutlaka ayrı kaydedin.')}},
  correctedNa:{title:'Düzeltilmiş Sodyum',short:'Düzeltilmiş Na',description:'Hiperglisemiye bağlı sodyum düşüşünü Katz katsayısıyla düzeltir.',sections:[['Laboratuvar',[num('na','Ölçülen sodyum','mmol/L',80,200,.1),num('glucose','Glukoz','mg/dL',20,2000,1)]]],calc:v=>{const s=v.glucose>100?v.na+1.6*((v.glucose-100)/100):v.na;return res(s.toFixed(1),'Düzeltilmiş sodyum',`Katz formülüyle hesaplanan değer ${s.toFixed(1)} mmol/L.`,'low','Ağır hiperglisemide farklı düzeltme katsayıları önerilebilir; klinik bağlamla yorumlayın.')}},
  anionGap:{title:'Anyon Açığı',short:'Anyon açığı',description:'Anyon açığını ve albümin varsa düzeltilmiş değeri hesaplar.',sections:[['Laboratuvar',[num('na','Sodyum','mmol/L',80,200,.1),num('cl','Klor','mmol/L',50,180,.1),num('hco3','Bikarbonat','mmol/L',0,60,.1),num('albumin','Albümin','g/dL',0,8,.1,'Opsiyonel; düzeltilmiş anyon açığı için',false)]]],calc:v=>{const ag=v.na-v.cl-v.hco3,corrected=v.albumin==null?null:ag+2.5*(4-v.albumin),display=corrected==null?ag.toFixed(1):`${ag.toFixed(1)} · düzeltilmiş ${corrected.toFixed(1)}`;return res(display,'Anyon açığı',corrected==null?`Hesaplanan anyon açığı ${ag.toFixed(1)} mmol/L.`:`Anyon açığı ${ag.toFixed(1)}, albümine göre düzeltilmiş ${corrected.toFixed(1)} mmol/L.`,ag>12?'mid':'low','Referans aralığı laboratuvara ve potasyumun formüle dahil edilmesine göre değişir.')}},
  correctedCa:{title:'Düzeltilmiş Kalsiyum',short:'Düzeltilmiş Ca',description:'Total kalsiyumu serum albüminine göre düzeltir.',sections:[['Laboratuvar',[num('ca','Total kalsiyum','mg/dL',1,20,.1),num('albumin','Albümin','g/dL',0,8,.1)]]],calc:v=>{const s=v.ca+.8*(4-v.albumin);return res(s.toFixed(2),'Düzeltilmiş total kalsiyum',`Albümine göre düzeltilmiş kalsiyum ${s.toFixed(2)} mg/dL.`,'low','Kritik hastalık, böbrek yetersizliği ve asit-baz bozukluğunda iyonize kalsiyum tercih edilir.')}},
  osmolality:{title:'Serum Osmolalitesi / Osmolal Açık',short:'Osmolalite',description:'Hesaplanan serum osmolalitesini ve ölçüm varsa osmolal açığı verir.',sections:[['Laboratuvar',[num('na','Sodyum','mmol/L',80,200,.1),num('glucose','Glukoz','mg/dL',0,2000,1),num('bun','BUN','mg/dL',0,300,.1),num('measured','Ölçülen osmolalite','mOsm/kg',150,500,.1,'Opsiyonel; osmolal açık için',false)]]],calc:v=>{const calc=2*v.na+v.glucose/18+v.bun/2.8,gap=v.measured==null?null:v.measured-calc,display=gap==null?calc.toFixed(1):`${calc.toFixed(1)} · açık ${gap.toFixed(1)}`;return res(display,'Serum osmolalitesi',gap==null?`Hesaplanan osmolalite ${calc.toFixed(1)} mOsm/kg.`:`Hesaplanan osmolalite ${calc.toFixed(1)} mOsm/kg; osmolal açık ${gap.toFixed(1)} mOsm/kg.`,gap!=null&&gap>10?'mid':'low','Etanol katkısı bu formüle dahil değildir; toksik alkol şüphesinde zamanlama ve klinikle yorumlayın.')}},
  qtc:{title:'QTc',short:'QTc',description:'Kalp hızı ve QT süresinden Bazett ve Fridericia QTc hesaplar.',sections:[['EKG',[choice('sex','Cinsiyet',[['male','Erkek'],['female','Kadın']]),num('hr','Kalp hızı','/dk',20,250,1),num('qt','Ölçülen QT','ms',100,900,1)]]],calc:v=>{const rr=60/v.hr,b=v.qt/Math.sqrt(rr),f=v.qt/Math.cbrt(rr),limit=v.sex==='male'?450:460,max=Math.max(b,f);return max>=500?res(`B ${Math.round(b)} · F ${Math.round(f)} ms`,'Belirgin QT uzaması','QTc ≥500 ms aritmi riski açısından önemlidir; ilaçlar, elektrolitler ve klinik durum değerlendirilmelidir.','high'):max>limit?res(`B ${Math.round(b)} · F ${Math.round(f)} ms`,'QTc uzamış','Cinsiyete göre referans üst sınırının üzerinde.','mid'):res(`B ${Math.round(b)} · F ${Math.round(f)} ms`,'QTc referans aralıkta','Bazett ve Fridericia sonuçları referans aralıkta.','low','Taşikardide Bazett aşırı, bradikardide eksik düzeltme yapabilir; manuel QT ölçümünü doğrulayın.')}},
  ibw:{title:'İdeal Vücut Ağırlığı',short:'İdeal vücut ağırlığı',description:'Devine formülüyle ideal vücut ağırlığını hesaplar.',sections:[['Hasta bilgileri',[choice('sex','Cinsiyet',[['male','Erkek'],['female','Kadın']]),num('height','Boy','cm',120,230,.1)]]],calc:v=>{const inches=v.height/2.54,base=v.sex==='male'?50:45.5,s=base+2.3*(inches-60);return res(`${s.toFixed(1)} kg`,'İdeal vücut ağırlığı',`Devine formülüne göre yaklaşık ${s.toFixed(1)} kg.`,'low','Ventilatör tidal volümü için öngörülen vücut ağırlığına yakın bir pratik tahmindir; ilaç dozları ilaca özgü ağırlık türüyle hesaplanmalıdır.')}},
  sfsr:{title:'San Francisco Senkop Kuralı',short:'San Francisco',description:'Senkopta kısa dönem ciddi sonuç açısından yüksek risk özelliklerini tarar.',sections:[['CHESS ölçütleri',[yes('chf','Kalp yetersizliği öyküsü'),yes('hct','Hematokrit <%30'),yes('ecg','Anormal EKG','Yeni değişiklik veya sinüs dışı ritim'),yes('sob','Nefes darlığı'),yes('sbp','Triyaj sistolik KB <90 mmHg')]]],calc:v=>{const s=sumToggles(v);return s===0?res(0,'Yüksek risk ölçütü yok','CHESS ölçütlerinin hiçbiri yok. Kural ciddi sonuç açısından düşük risk grubunu destekler.','low'):res(s,'Yüksek risk','En az bir CHESS ölçütü mevcut. Kısa dönem ciddi sonuç riski nedeniyle ileri değerlendirme gerekir.','high','Bağımsız doğrulamalarda performans değişkendir; klinik değerlendirme yerine kullanılmamalıdır.')}},
  ventHypox:{title:'Erişkin Hipoksemik Solunum Yetmezliği',short:'Hipoksemik ventilasyon',description:'ARDS, hipertansif akciğer ödemi ve diğer hipoksemik tablolar için başlangıç desteği.',population:'Erişkin hastalarda başlangıç önerisidir; NIV uygunluğu ve entübasyon kararı klinisyen tarafından belirlenir.',sections:[['Hasta ve klinik fenotip',[choice('sex','Cinsiyet',[['male','Erkek'],['female','Kadın']]),num('height','Boy','cm',140,220,.1,'Devine ideal/öngörülen vücut ağırlığı için'),choice('phenotype','Baskın klinik tablo',[['ards','ARDS / diffüz akciğer hasarı'],['edema','Hipertansif akciğer ödemi'],['other','Diğer hipoksemik yetmezlik']])]]],calc:v=>{const w=adultPBW(v),vt=round10(w*6);if(v.phenotype==='edema')return res('CPAP 10','NIV / CPAP öncelikli','Kooperasyon ve havayolu güvenliği uygunsa CPAP’ı gecikmeden başlatın; vazodilatör ve nedene yönelik tedaviyi eş zamanlı yürütün.','mid','Hipotansiyon, bilinç bozukluğu, sekresyon yönetememe veya hızla kötüleşmede NIV’yi uzatmadan entübasyonu değerlendirin.',[['Mod','CPAP'],['Basınç','10 cmH₂O'],['FiO₂','1,0 → hızla titre et'],['SpO₂ hedefi','%94–98'],['Yeniden değerlendirme','15–30 dk'],['İnvaziv yedek VT',`${vt} mL (6 mL/kg PBW)`],['PBW',`${w.toFixed(1)} kg`]]);const ards=v.phenotype==='ards';return res(`${vt} mL`,ards?'ARDS koruyucu ventilasyon':'Koruyucu başlangıç ventilasyonu',`Başlangıç tidal volümü ${w.toFixed(1)} kg öngörülen vücut ağırlığı üzerinden hesaplandı. Oksijenasyon, plato basıncı ve kan gazına göre erken titrasyon yapın.`,'mid',ards?'Plato basıncı <30 cmH₂O tutulmalı; ağır ARDS’de pron pozisyon ve ileri ARDS yaklaşımını değerlendirin.':'Nedeni tedavi edin; PEEP’i hemodinami ve oksijenasyona göre ayarlayın.',[['Mod','VC-A/C veya PRVC'],['VT',`${vt} mL (6 mL/kg PBW)`],['Solunum sayısı',ards?'20/dk':'16/dk'],['PEEP',ards?'8–10 cmH₂O':'8 cmH₂O'],['FiO₂','1,0 → hızla titre et'],['I:E','1:2'],['Oksijen hedefi',ards?'SpO₂ %88–95 / PaO₂ 55–80':'SpO₂ %92–96'],['PBW',`${w.toFixed(1)} kg`]])}},
  ventHypercap:{title:'Erişkin Hiperkarbik Solunum Yetmezliği',short:'Hiperkarbik ventilasyon',description:'KOAH gibi obstrüktif hastalıklarda NIV veya invaziv başlangıç ayarları.',population:'Erişkin akut veya akut-kronik hiperkarbik solunum yetmezliğinde başlangıç önerisidir.',sections:[['Hasta ve destek yolu',[choice('sex','Cinsiyet',[['male','Erkek'],['female','Kadın']]),num('height','Boy','cm',140,220,.1,'Entübasyon gerekirse tidal volüm hesabı için'),choice('route','Başlangıç destek yolu',[['niv','NIV için uygun'],['invasive','Entübe / invaziv gerekli']],'Havayolu güvenliği, bilinç, sekresyon ve hemodinamiye göre')]]],calc:v=>{const w=adultPBW(v),vt=round10(w*7);if(v.route==='niv')return res('12 / 5','Bilevel NIV başlangıcı','IPAP’ı solunum işi, tidal volüm ve kan gazına göre 2–3 cmH₂O basamaklarla artırın; ilk saatte klinik ve kan gazı yanıtını kontrol edin.','mid','NIV başarısızlığı bulgularında entübasyonu geciktirmeyin. Oksijeni %88–92 satürasyon hedefiyle verin.',[['Mod','BiPAP S/T'],['IPAP','12 cmH₂O'],['EPAP','5 cmH₂O'],['Yedek hız','12/dk'],['FiO₂ hedefi','SpO₂ %88–92'],['IPAP titrasyonu','Genellikle 18–20’ye doğru'],['Kontrol','30–60 dk kan gazı'],['İnvaziv PBW',`${w.toFixed(1)} kg`]]);return res(`${vt} mL`,'Obstrüktif invaziv ventilasyon','Uzun ekspirasyon süresi verin; solunum sayısı ve dakika ventilasyonunu pH, oto-PEEP ve hastanın kronik PaCO₂ düzeyine göre ayarlayın.','high','PaCO₂’yi hızla normalleştirmeye çalışmayın. Dinamik hiperinflasyon, hipotansiyon ve barotravmayı aktif olarak izleyin.',[['Mod','VC-A/C'],['VT',`${vt} mL (7 mL/kg PBW)`],['Solunum sayısı','10–12/dk'],['PEEP','5 cmH₂O'],['I:E','1:4 (1:3–1:5)'],['İnspiratuvar akım','80–100 L/dk'],['FiO₂ hedefi','SpO₂ %88–92'],['PBW',`${w.toFixed(1)} kg`]])}},
  ventTrauma:{title:'Erişkin Travma Hastası',short:'Erişkin travma ventilasyonu',description:'Travma hastasında akciğer koruyucu başlangıç ventilasyonu ve nörolojik hedefler.',population:'Erişkin travma hastasında başlangıç önerisidir; kanama, toraks yaralanması ve TBI birlikte değerlendirilmelidir.',sections:[['Hasta bilgileri',[choice('sex','Cinsiyet',[['male','Erkek'],['female','Kadın']]),num('height','Boy','cm',140,220,.1),yes('tbi','Orta/ağır travmatik beyin hasarı şüphesi'),yes('shock','Hemorajik şok / belirgin hipotansiyon')]]],calc:v=>{const w=adultPBW(v),vt=round10(w*6),co2=v.tbi?'EtCO₂ 35–40; ABG ile doğrula':'EtCO₂ 35–45';return res(`${vt} mL`,'Travmada koruyucu başlangıç','Entübasyon sonrası tüp yerini dalga kapnografiyle doğrulayın. Ventilasyonu erken kan gazı, basınçlar ve toraks patolojisine göre ayarlayın.',v.shock?'high':'mid',v.shock?'Resüsitasyon önceliklidir; indüksiyon ve pozitif basınç kollapsı ağırlaştırabilir. PEEP artışlarında kan basıncını yakından izleyin.':v.tbi?'Profilaktik hiperventilasyondan kaçının; herniasyon bulgusu yoksa normokapni hedefleyin.':'Gizli pnömotoraks ve dinamik değişiklikler için seri değerlendirme yapın.',[['Mod','VC-A/C veya PRVC'],['VT',`${vt} mL (6 mL/kg PBW)`],['Solunum sayısı',v.tbi?'16/dk':'14/dk'],['PEEP','5 cmH₂O'],['FiO₂','1,0 → hızla titre et'],['I:E','1:2'],['CO₂ hedefi',co2],['SpO₂ hedefi','%94–98'],['PBW',`${w.toFixed(1)} kg`]])}},
  ventPostCpr:{title:'Erişkin Post-CPR / ROSC',short:'Post-CPR ventilasyonu',description:'Spontan dolaşım dönüşü sonrası oksijenasyon ve normokapni hedefli başlangıç ayarları.',population:'ROSC sağlanmış erişkin hastada başlangıç önerisidir.',sections:[['Hasta bilgileri',[choice('sex','Cinsiyet',[['male','Erkek'],['female','Kadın']]),num('height','Boy','cm',140,220,.1),yes('acidemia','Belirgin metabolik asidemi sürüyor','Dakika ventilasyonu bireyselleştirilmeli')]]],calc:v=>{const w=adultPBW(v),vt=round10(w*6);return res(`${vt} mL`,'Post-ROSC koruyucu ventilasyon','Başlangıçta güvenilir SpO₂ veya PaO₂ ölçülene kadar FiO₂ 1,0 kullanın; ardından hipoksemi ve hiperoksemiden kaçınacak şekilde hızla azaltın.','mid',v.acidemia?'Şiddetli asidemide solunum sayısını körlemesine sabitlemeyin; erken ABG ile yeterli dakika ventilasyonunu bireyselleştirin.':'PaCO₂’yi 35–45 mmHg aralığında tutun ve erken kan gazıyla EtCO₂–PaCO₂ farkını değerlendirin.',[['Mod','VC-A/C veya PRVC'],['VT',`${vt} mL (6 mL/kg PBW)`],['Solunum sayısı',v.acidemia?'16/dk başlangıç; ABG’ye göre':'14/dk'],['PEEP','5 cmH₂O'],['FiO₂','1,0 → SpO₂ %90–98'],['PaO₂ hedefi','60–105 mmHg'],['PaCO₂ hedefi',v.acidemia?'ABG’ye göre; sonra 35–45':'35–45 mmHg'],['I:E','1:2'],['PBW',`${w.toFixed(1)} kg`]])}},
  ventPedsTrauma:{title:'Pediatrik Travma Hastası',short:'Pediatrik travma ventilasyonu',description:'Çocuk travma hastasında ağırlık ve yaşa göre koruyucu başlangıç ventilasyonu.',population:'Yenidoğan dışı, 18 yaş altı travma hastasında başlangıç önerisidir; pediatri/yoğun bakım desteği erken istenmelidir.',sections:[['Hasta bilgileri',[num('age','Yaş','yıl',.1,17,.1),num('weight','Ventilatör hesaplama ağırlığı','kg',3,120,.1,'İdeal/kuru ağırlık; obezitede gerçek ağırlığı doğrudan kullanmayın'),yes('tbi','Orta/ağır travmatik beyin hasarı şüphesi'),yes('shock','Hemorajik şok / belirgin hipotansiyon')]]],calc:v=>{const vt=round5(v.weight*6),rr=v.age<1?25:v.age<6?20:v.age<13?16:14;return res(`${vt} mL`,'Pediatrik travma başlangıcı','Yaşa uygun devre ve tüp ile hacim kontrollü/garantili ventilasyon başlatın; göğüs ekspansiyonu, kaçak, kapnografi ve erken kan gazıyla doğrulayın.',v.shock?'high':'mid',v.tbi?'İlk 48 saatte profilaktik PaCO₂ <30 mmHg’den kaçının; herniasyon tedavisi dışında normokapniyi koruyun.':'Erişkin Devine formülü çocuklarda geçerli değildir; girilen ideal/kuru ventilatör ağırlığı kullanılmıştır.',[['Mod','VC-A/C veya hacim garantili'],['VT',`${vt} mL (6 mL/kg)`],['Solunum sayısı',`${rr}/dk`],['PEEP','5 cmH₂O'],['FiO₂','1,0 → hızla titre et'],['I:E','1:2'],['CO₂ hedefi',v.tbi?'EtCO₂ 35–40; ABG ile doğrula':'EtCO₂ 35–45'],['SpO₂ hedefi','%94–98'],['Plato basıncı','Tercihen <28 cmH₂O']])}}
};

function res(score,title,text,tone,note='',details=[]){return{score,title,text,tone,note,details}}
function sumToggles(v){return Object.values(v).filter(Boolean).length}
function band(value,bands){for(const [limit,pts] of bands)if(value<limit)return pts;return 0}
function adultPBW(v){const inches=v.height/2.54,base=v.sex==='male'?50:45.5;return Math.max(20,base+2.3*(inches-60))}
function round10(value){return Math.round(value/10)*10}
function round5(value){return Math.round(value/5)*5}

let currentCategory=null,currentScore=null;
const views={home:$('#homeView'),category:$('#categoryView'),calculator:$('#calculatorView')};

function showView(name){Object.entries(views).forEach(([k,v])=>v.classList.toggle('is-hidden',k!==name));$('#backButton').classList.toggle('is-hidden',name==='home');$('#resetButton').classList.toggle('is-hidden',name!=='calculator');window.scrollTo({top:0,behavior:'instant'});}

function normalizeSearch(value){return value.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i')}
function categorySearchText(c){const scoreText=c.scores.flatMap(id=>[scores[id].title,scores[id].short,scores[id].description]).join(' ');return normalizeSearch(`${c.title} ${c.subtitle} ${c.description} ${scoreText}`)}
function renderCategories(query=''){const grid=$('#categoryGrid'),empty=$('#searchEmpty'),status=$('#searchStatus'),clear=$('#clearSearch'),term=normalizeSearch(query.trim());grid.innerHTML='';const ordered=[...categories].sort((a,b)=>a.title.localeCompare(b.title,'tr-TR',{sensitivity:'base'}));const visible=term?ordered.filter(c=>categorySearchText(c).includes(term)):ordered;visible.forEach((c,index)=>{const matchingScores=term?c.scores.filter(id=>normalizeSearch(`${scores[id].title} ${scores[id].short} ${scores[id].description}`).includes(term)):[];const detail=matchingScores.length?matchingScores.map(id=>scores[id].short).join(' · '):c.subtitle;const b=document.createElement('button');b.type='button';b.className=`category-card tone-${index%8}`;b.innerHTML=`<span class="category-icon"><i data-lucide="${c.icon}" aria-hidden="true"></i></span><span><strong>${c.title}</strong><small>${detail}</small></span>`;b.onclick=()=>openCategory(c.id);grid.appendChild(b)});empty.classList.toggle('is-hidden',visible.length!==0);clear.classList.toggle('is-hidden',!query);status.textContent=term?`${visible.length} kategori bulundu`:'';if(window.lucide)lucide.createIcons({attrs:{'stroke-width':2.2}})}
function renderHome(){renderCategories($('#categorySearch').value);showView('home')}

function openCategory(id){currentCategory=categories.find(c=>c.id===id);$('#categoryTitle').textContent=currentCategory.title;$('#categoryDescription').textContent=currentCategory.description;const grid=$('#scoreGrid');grid.innerHTML='';currentCategory.scores.forEach(id=>{const s=scores[id],b=document.createElement('button');b.type='button';b.className='score-card';b.innerHTML=`<span><strong>${s.title}</strong><small>${s.description}</small></span><b>›</b>`;b.onclick=()=>openCalculator(id);grid.appendChild(b)});showView('category')}

function openCalculator(id){currentScore=id;const s=scores[id];$('#calculatorCategory').textContent=currentCategory.title.toUpperCase();$('#calculatorTitle').textContent=s.title;$('#calculatorDescription').textContent=s.description;const form=$('#calculatorForm');form.innerHTML='';s.sections.forEach(([title,fields])=>{const h=document.createElement('h2');h.className='section-label';h.textContent=title;form.appendChild(h);fields.forEach(f=>form.appendChild(renderField(f)))});form.oninput=calculate;$('#sourceContent').innerHTML=`<p>${sources[id]}</p><p>${s.population||'Hesaplayıcı yalnız erişkin hastalar ve skorun özgün kullanım popülasyonu için tasarlanmıştır.'}</p>`;resetResult();showView('calculator')}

function renderField(f){if(f.type==='toggle'){const e=$('#toggleTemplate').content.firstElementChild.cloneNode(true);e.querySelector('strong').textContent=f.label;e.querySelector('small').textContent=f.help;e.querySelector('input').name=f.id;return e}if(f.type==='number'){const e=$('#numberTemplate').content.firstElementChild.cloneNode(true),i=e.querySelector('input');e.querySelector('strong').textContent=f.label;e.querySelector('small').textContent=f.help;e.querySelector('em').textContent=f.unit;i.name=f.id;i.min=f.min;i.max=f.max;i.step=f.step;i.required=f.required;return e}const e=$('#selectTemplate').content.firstElementChild.cloneNode(true),box=e.querySelector('.segmented');e.querySelector('legend').textContent=f.label;e.querySelector('small').textContent=f.help;box.style.setProperty('--cols',Math.min(f.options.length,3));f.options.forEach(([value,label],idx)=>{const l=document.createElement('label');l.innerHTML=`<input type="radio" name="${f.id}" value="${value}" ${idx===-1?'checked':''}><span>${label}</span>`;box.appendChild(l)});return e}

function values(){const data={},form=$('#calculatorForm');form.querySelectorAll('input[type=checkbox]').forEach(i=>data[i.name]=i.checked);form.querySelectorAll('input[type=number]').forEach(i=>data[i.name]=i.value===''?null:+i.value);form.querySelectorAll('input[type=radio]:checked').forEach(i=>data[i.name]=i.value);return data}
function isComplete(){const form=$('#calculatorForm');let ok=true;form.querySelectorAll('.invalid').forEach(e=>e.classList.remove('invalid'));form.querySelectorAll('input[type=number]').forEach(i=>{if((i.required&&i.value==='')||(i.value!==''&&!i.checkValidity())){i.closest('.field-row').classList.add('invalid');ok=false}});const names=[...new Set([...form.querySelectorAll('input[type=radio]')].map(i=>i.name))];names.forEach(n=>{if(!form.querySelector(`input[name="${n}"]:checked`)){form.querySelector(`input[name="${n}"]`).closest('.choice-field').classList.add('invalid');ok=false}});return ok}
function calculate(){if(!isComplete()){resetResult();return}const r=scores[currentScore].calc(values()),card=$('#resultCard'),details=$('#resultDetails');card.className=`result-card ${r.tone}${r.details?.length?' has-details':''}`;$('#resultScore').textContent=r.score;$('#resultTitle').textContent=r.title;$('#resultText').textContent=r.text;details.innerHTML='';(r.details||[]).forEach(([label,value])=>{const row=document.createElement('div'),key=document.createElement('span'),val=document.createElement('strong');key.textContent=label;val.textContent=value;row.append(key,val);details.appendChild(row)});details.classList.toggle('is-hidden',!r.details?.length);$('#resultNote').textContent=r.note;$('#resultNote').classList.toggle('is-hidden',!r.note)}
function resetResult(){const card=$('#resultCard');card.className='result-card';$('#resultScore').textContent='—';$('#resultTitle').textContent='Alanları doldurun';$('#resultText').textContent='Sonuç, tüm zorunlu alanlar tamamlandığında burada görünecek.';$('#resultDetails').innerHTML='';$('#resultDetails').classList.add('is-hidden');$('#resultNote').textContent='';$('#resultNote').classList.add('is-hidden')}

$('#backButton').onclick=()=>{if(!views.calculator.classList.contains('is-hidden'))openCategory(currentCategory.id);else renderHome()};
$('#resetButton').onclick=()=>{$('#calculatorForm').reset();$('#calculatorForm').querySelectorAll('.invalid').forEach(e=>e.classList.remove('invalid'));resetResult()};
$('.brand').onclick=e=>{e.preventDefault();renderHome()};
$('#categorySearch').addEventListener('input',e=>renderCategories(e.target.value));
$('#clearSearch').onclick=()=>{const input=$('#categorySearch');input.value='';renderCategories();input.focus()};
window.addEventListener('popstate',renderHome);
renderHome();
